'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Sparkles, Loader2, AlertCircle, Check, X } from 'lucide-react'
import { toast } from 'sonner'
import { useRegionsStore, type City } from '@/stores/region-store'
import type { DailyItinerary, FlightInfo } from '../../types'

interface AutoGenerateDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onGenerate: (dailyItinerary: DailyItinerary[]) => void
  // 現有資料（用於預填）
  currentCity?: string
  currentDepartureDate?: string
  currentOutboundFlight?: FlightInfo
  currentReturnFlight?: FlightInfo
  currentDays?: number
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onGenerate,
  currentCity,
  currentDepartureDate,
  currentOutboundFlight,
  currentReturnFlight,
  currentDays,
}: AutoGenerateDialogProps) {
  // 狀態
  const [cityId, setCityId] = useState<string>('')
  const [numDays, setNumDays] = useState(currentDays || 5)
  const [departureDate, setDepartureDate] = useState(currentDepartureDate || '')
  const [arrivalTime, setArrivalTime] = useState(currentOutboundFlight?.arrivalTime || '11:00')
  const [departureTime, setDepartureTime] = useState(currentReturnFlight?.departureTime || '14:00')
  const [isGenerating, setIsGenerating] = useState(false)
  const [result, setResult] = useState<{
    success: boolean
    stats?: { totalAttractions: number; attractionsInDb: number }
    warnings?: string[]
  } | null>(null)

  // 載入城市資料
  const { cities, loading: citiesLoading, fetchAll } = useRegionsStore()

  useEffect(() => {
    if (open && cities.length === 0) {
      fetchAll()
    }
  }, [open, cities.length, fetchAll])

  // 當 currentCity 變化時，嘗試找到對應的 cityId
  useEffect(() => {
    if (currentCity && cities.length > 0) {
      const matchedCity = cities.find(
        (c: City) => c.name === currentCity || c.name?.includes(currentCity)
      )
      if (matchedCity) {
        setCityId(matchedCity.id)
      }
    }
  }, [currentCity, cities])

  // 預填航班時間
  useEffect(() => {
    if (currentOutboundFlight?.arrivalTime) {
      setArrivalTime(currentOutboundFlight.arrivalTime)
    }
    if (currentReturnFlight?.departureTime) {
      setDepartureTime(currentReturnFlight.departureTime)
    }
  }, [currentOutboundFlight, currentReturnFlight])

  // 重置狀態
  const handleClose = () => {
    setResult(null)
    onOpenChange(false)
  }

  // 執行生成
  const handleGenerate = async () => {
    if (!cityId) {
      toast.error('請選擇城市')
      return
    }
    if (!departureDate) {
      toast.error('請選擇出發日期')
      return
    }
    if (!arrivalTime || !departureTime) {
      toast.error('請填寫航班時間')
      return
    }

    setIsGenerating(true)
    setResult(null)

    try {
      const response = await fetch('/api/itineraries/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cityId,
          numDays,
          departureDate,
          outboundFlight: { arrivalTime },
          returnFlight: { departureTime },
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || '生成失敗')
      }

      if (data.success) {
        setResult({
          success: true,
          stats: data.data.stats,
          warnings: data.warnings,
        })

        // 轉換為前端格式
        const dailyItinerary = data.data.dailyItinerary.map((day: DailyItinerary) => ({
          ...day,
          isAlternative: false,
        }))

        onGenerate(dailyItinerary)
        toast.success(`成功生成 ${numDays} 天行程！`)

        // 延遲關閉，讓使用者看到結果
        setTimeout(() => {
          handleClose()
        }, 1500)
      } else {
        throw new Error('生成失敗')
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : '生成失敗，請稍後再試')
      setResult({ success: false })
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="text-morandi-gold" size={20} />
            一鍵生成行程
          </DialogTitle>
          <DialogDescription>
            根據您的航班時間和目的地，自動從資料庫規劃最佳行程
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* 城市選擇 */}
          <div className="space-y-2">
            <Label>目的地城市</Label>
            <Select value={cityId} onValueChange={setCityId}>
              <SelectTrigger>
                <SelectValue placeholder={citiesLoading ? '載入中...' : '選擇城市'} />
              </SelectTrigger>
              <SelectContent>
                {cities.map((city: City) => (
                  <SelectItem key={city.id} value={city.id}>
                    {city.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* 天數和日期 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>行程天數</Label>
              <Input
                type="number"
                value={numDays}
                onChange={e => setNumDays(Math.max(1, Math.min(30, parseInt(e.target.value) || 1)))}
                min={1}
                max={30}
              />
            </div>
            <div className="space-y-2">
              <Label>出發日期</Label>
              <Input
                type="date"
                value={departureDate}
                onChange={e => setDepartureDate(e.target.value)}
              />
            </div>
          </div>

          {/* 航班時間 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>去程抵達時間</Label>
              <Input
                type="time"
                value={arrivalTime}
                onChange={e => setArrivalTime(e.target.value)}
                placeholder="11:00"
              />
              <p className="text-xs text-morandi-secondary">
                抵達 1 小時後開始行程
              </p>
            </div>
            <div className="space-y-2">
              <Label>回程起飛時間</Label>
              <Input
                type="time"
                value={departureTime}
                onChange={e => setDepartureTime(e.target.value)}
                placeholder="14:00"
              />
              <p className="text-xs text-morandi-secondary">
                起飛前 2 小時結束行程
              </p>
            </div>
          </div>

          {/* 結果顯示 */}
          {result && (
            <div className={`p-4 rounded-lg ${result.success ? 'bg-green-50' : 'bg-red-50'}`}>
              {result.success ? (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-green-700">
                    <Check size={18} />
                    <span className="font-medium">生成成功！</span>
                  </div>
                  {result.stats && (
                    <p className="text-sm text-green-600">
                      使用了 {result.stats.totalAttractions} 個景點
                      （資料庫共 {result.stats.attractionsInDb} 個）
                    </p>
                  )}
                  {result.warnings && result.warnings.length > 0 && (
                    <div className="mt-2 text-sm text-amber-600">
                      {result.warnings.map((w, i) => (
                        <p key={i}>⚠️ {w}</p>
                      ))}
                    </div>
                  )}
                </div>
              ) : (
                <div className="flex items-center gap-2 text-red-700">
                  <AlertCircle size={18} />
                  <span>生成失敗，請重試</span>
                </div>
              )}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" className="gap-1" onClick={handleClose} disabled={isGenerating}>
            <X size={16} />
            取消
          </Button>
          <Button
            onClick={handleGenerate}
            disabled={isGenerating || !cityId}
            className="bg-morandi-gold hover:bg-morandi-gold-hover text-white gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                生成中...
              </>
            ) : (
              <>
                <Sparkles size={16} />
                開始生成
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
