'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Sparkles, Loader2, AlertCircle, Check, X, Plus, Trash2, GripVertical } from 'lucide-react'
import { toast } from 'sonner'
import { useCities, type City } from '@/data'
import type { DailyItinerary, FlightInfo } from '../../types'
import type { AccommodationPlan, ItineraryStyle } from '@/lib/itinerary-generator/types'
import { COMP_EDITOR_LABELS } from '../../../constants/labels'

interface AutoGenerateDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onGenerate: (dailyItinerary: DailyItinerary[]) => void
  // 現有資料（用於預填）
  currentCity?: string
  currentDepartureDate?: string
  currentOutboundFlight?: FlightInfo
  currentReturnFlight?: FlightInfo
  currentDays?: number
}

// 風格選項
const STYLE_OPTIONS: { value: ItineraryStyle; label: string; icon: string; description: string }[] = [
  { value: 'relax', label: COMP_EDITOR_LABELS.悠閒慢活, icon: '🌿', description: COMP_EDITOR_LABELS.放慢腳步_每天_2_3_個景點 },
  { value: 'adventure', label: COMP_EDITOR_LABELS.冒險探索, icon: '🏔️', description: COMP_EDITOR_LABELS.深度體驗_探索隱藏景點 },
  { value: 'culture', label: COMP_EDITOR_LABELS.文化巡禮, icon: '🏛️', description: COMP_EDITOR_LABELS.歷史古蹟_博物館為主 },
  { value: 'food', label: COMP_EDITOR_LABELS.美食之旅, icon: '🍜', description: COMP_EDITOR_LABELS.在地美食_市場巡禮 },
]

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onGenerate,
  currentCity,
  currentDepartureDate,
  currentOutboundFlight,
  currentReturnFlight,
  currentDays,
}: AutoGenerateDialogProps) {
  // 狀態
  const [cityId, setCityId] = useState<string>('')
  const [numDays, setNumDays] = useState(currentDays || 5)
  const [departureDate, setDepartureDate] = useState(currentDepartureDate || '')
  const [arrivalTime, setArrivalTime] = useState(currentOutboundFlight?.arrivalTime || '11:00')
  const [departureTime, setDepartureTime] = useState(currentReturnFlight?.departureTime || '14:00')
  const [isGenerating, setIsGenerating] = useState(false)
  const [result, setResult] = useState<{
    success: boolean
    stats?: { totalAttractions: number; attractionsInDb: number }
    warnings?: string[]
  } | null>(null)

  // 新增：住宿安排
  const [accommodations, setAccommodations] = useState<AccommodationPlan[]>([])
  const [style, setStyle] = useState<ItineraryStyle>('relax')

  // 載入城市資料 (SWR 自動載入)
  const { items: cities, loading: citiesLoading } = useCities()

  // 當 currentCity 變化時，嘗試找到對應的 cityId
  useEffect(() => {
    if (currentCity && cities.length > 0) {
      const matchedCity = cities.find(
        (c: City) => c.name === currentCity || c.name?.includes(currentCity)
      )
      if (matchedCity) {
        setCityId(matchedCity.id)
      }
    }
  }, [currentCity, cities])

  // 預填航班時間
  useEffect(() => {
    if (currentOutboundFlight?.arrivalTime) {
      setArrivalTime(currentOutboundFlight.arrivalTime)
    }
    if (currentReturnFlight?.departureTime) {
      setDepartureTime(currentReturnFlight.departureTime)
    }
  }, [currentOutboundFlight, currentReturnFlight])

  // 重置狀態
  const handleClose = () => {
    setResult(null)
    onOpenChange(false)
  }

  // 住宿安排：新增城市
  const addAccommodation = () => {
    setAccommodations([...accommodations, { cityId: '', cityName: '', nights: 1 }])
  }

  // 住宿安排：移除城市
  const removeAccommodation = (index: number) => {
    setAccommodations(accommodations.filter((_, i) => i !== index))
  }

  // 住宿安排：更新城市
  const updateAccommodation = (index: number, field: keyof AccommodationPlan, value: string | number) => {
    const newAccommodations = [...accommodations]
    if (field === 'cityId') {
      const city = cities.find((c: City) => c.id === value)
      newAccommodations[index] = {
        ...newAccommodations[index],
        cityId: value as string,
        cityName: city?.name || '',
      }
    } else {
      newAccommodations[index] = { ...newAccommodations[index], [field]: value }
    }
    setAccommodations(newAccommodations)
  }

  // 計算住宿總晚數
  const totalNights = accommodations.reduce((sum, a) => sum + a.nights, 0)
  const expectedNights = numDays - 1 // 天數 - 1 = 夜數

  // 執行生成
  const handleGenerate = async () => {
    if (!cityId) {
      toast.error(COMP_EDITOR_LABELS.請選擇城市)
      return
    }
    if (!departureDate) {
      toast.error(COMP_EDITOR_LABELS.請選擇出發日期)
      return
    }
    if (!arrivalTime || !departureTime) {
      toast.error(COMP_EDITOR_LABELS.請填寫航班時間)
      return
    }

    setIsGenerating(true)
    setResult(null)

    try {
      const response = await fetch('/api/itineraries/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          cityId,
          numDays,
          departureDate,
          outboundFlight: { arrivalTime },
          returnFlight: { departureTime },
          // 新增：住宿安排和風格
          accommodations: accommodations.length > 0 ? accommodations : undefined,
          style,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || COMP_EDITOR_LABELS.生成失敗)
      }

      if (data.success) {
        setResult({
          success: true,
          stats: data.data.stats,
          warnings: data.warnings,
        })

        // 轉換為前端格式
        const dailyItinerary = data.data.dailyItinerary.map((day: DailyItinerary) => ({
          ...day,
          isAlternative: false,
        }))

        onGenerate(dailyItinerary)
        toast.success(`成功生成 ${numDays} 天行程！`)

        // 延遲關閉，讓使用者看到結果
        setTimeout(() => {
          handleClose()
        }, 1500)
      } else {
        throw new Error(COMP_EDITOR_LABELS.生成失敗)
      }
    } catch (error) {
      toast.error(error instanceof Error ? error.message : COMP_EDITOR_LABELS.生成失敗_請稍後再試)
      setResult({ success: false })
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent level={1} className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="text-morandi-gold" size={20} />
            一鍵生成行程
          </DialogTitle>
          <DialogDescription>
            根據您的航班時間和目的地，自動從資料庫規劃最佳行程
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* 城市選擇 */}
          <div className="space-y-2">
            <Label>目的地城市</Label>
            <Select value={cityId} onValueChange={setCityId}>
              <SelectTrigger>
                <SelectValue placeholder={citiesLoading ? COMP_EDITOR_LABELS.載入中 : COMP_EDITOR_LABELS.選擇城市} />
              </SelectTrigger>
              <SelectContent>
                {cities.map((city: City) => (
                  <SelectItem key={city.id} value={city.id}>
                    {city.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* 天數和日期 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>行程天數</Label>
              <Input
                type="number"
                value={numDays}
                onChange={e => setNumDays(Math.max(1, Math.min(30, parseInt(e.target.value) || 1)))}
                min={1}
                max={30}
              />
            </div>
            <div className="space-y-2">
              <Label>出發日期</Label>
              <Input
                type="date"
                value={departureDate}
                onChange={e => setDepartureDate(e.target.value)}
              />
            </div>
          </div>

          {/* 航班時間 */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>去程抵達時間</Label>
              <Input
                type="time"
                value={arrivalTime}
                onChange={e => setArrivalTime(e.target.value)}
                placeholder="11:00"
              />
              <p className="text-xs text-morandi-secondary">
                抵達 1 小時後開始行程
              </p>
            </div>
            <div className="space-y-2">
              <Label>回程起飛時間</Label>
              <Input
                type="time"
                value={departureTime}
                onChange={e => setDepartureTime(e.target.value)}
                placeholder="14:00"
              />
              <p className="text-xs text-morandi-secondary">
                起飛前 2 小時結束行程
              </p>
            </div>
          </div>

          {/* 行程風格 */}
          <div className="space-y-2">
            <Label>行程風格</Label>
            <div className="grid grid-cols-2 gap-2">
              {STYLE_OPTIONS.map((option) => (
                <button
                  key={option.value}
                  type="button"
                  onClick={() => setStyle(option.value)}
                  className={`p-3 rounded-lg border text-left transition-all ${
                    style === option.value
                      ? 'border-morandi-gold bg-morandi-gold/10'
                      : 'border-border hover:border-morandi-gold/50'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{option.icon}</span>
                    <span className="font-medium text-sm">{option.label}</span>
                  </div>
                  <p className="text-xs text-morandi-secondary mt-1">{option.description}</p>
                </button>
              ))}
            </div>
          </div>

          {/* 住宿安排 */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Label>住宿安排（選填）</Label>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={addAccommodation}
                className="h-7 text-xs gap-1"
              >
                <Plus size={14} />
                新增城市
              </Button>
            </div>
            <p className="text-xs text-morandi-secondary">
              指定住宿城市可讓行程更精準。例如：大阪進但住京都，會優先安排京都景點。
            </p>

            {accommodations.length > 0 && (
              <div className="space-y-2">
                {accommodations.map((acc, index) => (
                  <div key={index} className="flex items-center gap-2 p-2 bg-muted rounded-lg">
                    <GripVertical size={14} className="text-morandi-secondary cursor-grab" />
                    <div className="flex-1 grid grid-cols-2 gap-2">
                      <Select
                        value={acc.cityId}
                        onValueChange={(value) => updateAccommodation(index, 'cityId', value)}
                      >
                        <SelectTrigger className="h-8 text-sm">
                          <SelectValue placeholder={COMP_EDITOR_LABELS.選擇城市} />
                        </SelectTrigger>
                        <SelectContent>
                          {cities.map((city: City) => (
                            <SelectItem key={city.id} value={city.id}>
                              {city.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <div className="flex items-center gap-2">
                        <Input
                          type="number"
                          value={acc.nights}
                          onChange={(e) => updateAccommodation(index, 'nights', Math.max(1, parseInt(e.target.value) || 1))}
                          min={1}
                          max={numDays - 1}
                          className="h-8 text-sm w-16"
                        />
                        <span className="text-sm text-morandi-secondary">晚</span>
                      </div>
                    </div>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => removeAccommodation(index)}
                      className="h-8 w-8 p-0 text-morandi-red hover:text-morandi-red hover:bg-morandi-red/10"
                    >
                      <Trash2 size={14} />
                    </Button>
                  </div>
                ))}

                {/* 夜數檢查 */}
                {totalNights > 0 && (
                  <div className={`text-xs p-2 rounded ${
                    totalNights === expectedNights
                      ? 'bg-green-50 text-green-700'
                      : totalNights > expectedNights
                      ? 'bg-red-50 text-red-700'
                      : 'bg-amber-50 text-amber-700'
                  }`}>
                    {totalNights === expectedNights ? (
                      <span className="flex items-center gap-1">
                        <Check size={12} />
                        住宿安排完成：{totalNights} 晚
                      </span>
                    ) : totalNights > expectedNights ? (
                      <span className="flex items-center gap-1">
                        <AlertCircle size={12} />
                        住宿晚數（{totalNights}）超過行程夜數（{expectedNights}）
                      </span>
                    ) : (
                      <span className="flex items-center gap-1">
                        <AlertCircle size={12} />
                        還有 {expectedNights - totalNights} 晚未安排住宿
                      </span>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* 結果顯示 */}
          {result && (
            <div className={`p-4 rounded-lg ${result.success ? 'bg-green-50' : 'bg-red-50'}`}>
              {result.success ? (
                <div className="space-y-2">
                  <div className="flex items-center gap-2 text-green-700">
                    <Check size={18} />
                    <span className="font-medium">生成成功！</span>
                  </div>
                  {result.stats && (
                    <p className="text-sm text-green-600">
                      使用了 {result.stats.totalAttractions} 個景點
                      （資料庫共 {result.stats.attractionsInDb} 個）
                    </p>
                  )}
                  {result.warnings && result.warnings.length > 0 && (
                    <div className="mt-2 text-sm text-amber-600">
                      {result.warnings.map((w, i) => (
                        <p key={i}>⚠️ {w}</p>
                      ))}
                    </div>
                  )}
                </div>
              ) : (
                <div className="flex items-center gap-2 text-red-700">
                  <AlertCircle size={18} />
                  <span>生成失敗，請重試</span>
                </div>
              )}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" className="gap-1" onClick={handleClose} disabled={isGenerating}>
            <X size={16} />
            取消
          </Button>
          <Button
            onClick={handleGenerate}
            disabled={isGenerating || !cityId}
            className="bg-morandi-gold hover:bg-morandi-gold-hover text-white gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 size={16} className="animate-spin" />
                生成中...
              </>
            ) : (
              <>
                <Sparkles size={16} />
                開始生成
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
