// 顧客模組 UI 標籤常量

export const CUSTOMER_PAGE_LABELS = {
  page_title: '顧客管理',
  btn_groups: '群組',
  btn_advanced_search: '進階搜尋',
  btn_clear_filters: '清除條件',
  btn_add_customer: '新增顧客',
  filter_applied: (count: number, shown: number, total: number) =>
    `已套用 ${count} 個篩選條件 | 顯示 ${shown} / ${total} 位顧客`,
  title_verify: '驗證顧客資料',
  title_edit: '編輯顧客',
  title_delete: '刪除顧客',
  col_code: '編號',
  col_name: '中文姓名',
  col_passport_name: '護照拼音',
  col_phone: '電話',
  col_passport_number: '護照號碼',
  col_passport_expiry: '護照效期',
  col_national_id: '身分證號',
  col_birth_date: '生日',
  col_dietary: '飲食禁忌',
  col_vip: 'VIP',
  vip_normal: '一般',
  unknown_order: '未知訂單',
  confirm_delete: (name: string) => `確定要刪除顧客「${name}」嗎？`,
  confirm_delete_title: '刪除顧客',
  cannot_delete_title: '無法刪除顧客',
  cannot_delete_msg: (orders: string) =>
    `此顧客已被以下訂單使用：${orders}\n\n請先到訂單中移除該成員後，再刪除顧客。`,
  btn_go_to_order: '前往訂單',
  btn_cancel: '取消',
}

export const CUSTOMER_ADD_LABELS = {
  title: '新增顧客',
  confirm_close_title: '放棄新增？',
  confirm_close_msg: '已輸入的顧客資料尚未保存，確定要關閉嗎？',
  confirm_close_label: '放棄',
  cancel_close_label: '繼續填寫',
  section_manual: '手動輸入',
  section_manual_desc: '手動填寫顧客基本資訊與護照資料',
  label_name: '姓名',
  label_phone: '電話',
  label_national_id: '身份證字號',
  label_passport_name: '護照拼音',
  label_passport_number: '護照號碼',
  label_passport_expiry: '護照效期',
  label_birth_date: '出生日期',
  placeholder_name: '輸入顧客姓名',
  placeholder_phone: '輸入聯絡電話',
  placeholder_national_id: '身份證字號',
  placeholder_passport_name: '例如：WANG/XIAOMING',
  placeholder_passport_number: '護照號碼',
  placeholder_date: '選擇日期',
  btn_add_manual: '手動新增顧客',
  section_ocr: '上傳護照辨識',
  section_ocr_desc: '上傳護照圖片，自動辨識並建立顧客資料',
  upload_click: '點擊上傳',
  upload_drag: '或拖曳檔案',
  upload_formats: '支援 JPG, PNG, PDF（可多選）',
  ocr_processing: '辨識中...',
  ocr_process_btn: (count: number) => `辨識並建立 ${count} 位顧客`,
  files_selected: (count: number) => `已選擇 ${count} 個檔案：`,
  section_reminder: '重要提醒',
  reminder_1: 'OCR 辨識的資料會自動標記為',
  reminder_1_strong: '「待驗證」',
  reminder_2_prefix: '請務必',
  reminder_2_strong: '人工檢查護照資訊',
  reminder_3: '支援所有國家護照（TWN、USA、JPN 等）',
  section_tips: '拍攝建議',
  tip_1_prefix: '確保護照',
  tip_1_strong: '最下方兩排文字',
  tip_1_suffix: '清晰可見',
  tip_2: '光線充足，避免反光或陰影',
  tip_3: '拍攝角度正面，避免傾斜',
  btn_cancel: '取消',
}

export const CUSTOMER_DETAIL_LABELS = {
  passport_alt: (name: string) => `${name} 護照照片`,
  no_passport_photo: '尚無護照照片',
  label_phone: '電話',
  label_email: 'Email',
  section_passport: '護照資料',
  label_passport_number: '護照號碼',
  label_passport_name: '護照拼音',
  label_passport_expiry: '護照效期',
  label_verification: '驗證狀態',
  status_verified: '已驗證',
  status_unverified: '待驗證',
  section_identity: '身分資料',
  label_national_id: '身分證號',
  label_birth_date: '生日',
  label_dietary: '飲食禁忌',
  btn_close: '關閉',
  btn_edit: '編輯資料',
}

export const RESET_PASSWORD_LABELS = {
  title: '重置會員密碼',
  resetting_for: '正在為',
  reset_password_suffix: '重置密碼',
  account_label: '會員帳號：',
  no_email: '無 Email',
  label_new_password: '新密碼',
  placeholder_password: '請輸入新密碼（至少 6 個字元）',
  no_email_warning: '此顧客沒有設定 Email，無法重置密碼。請先在顧客資料中填寫 Email。',
  btn_cancel: '取消',
  btn_confirm: '確認重置',
  btn_resetting: '重置中...',
  toast_enter_password: '請輸入新密碼',
  toast_min_length: '密碼至少需要 6 個字元',
  confirm_msg: (name: string) => `確定要將 ${name} 的密碼重置為新密碼嗎？`,
  confirm_title: '確認重置密碼',
  confirm_text: '確認重置',
  toast_success: '密碼已重置成功',
  toast_failed: '重置密碼失敗',
}

export const CUSTOMER_SEARCH_LABELS = {
  title: '進階搜尋',
  section_basic: '基本條件',
  label_keyword: '關鍵字',
  placeholder_keyword: '輸入姓名、身份證號或護照號碼',
  label_phone: '電話',
  placeholder_phone: '輸入電話號碼',
  label_email: 'Email',
  placeholder_email: '輸入 Email',
  label_city: '城市',
  placeholder_city: '輸入城市',
  section_passport: '護照條件',
  label_passport_name: '護照拼音',
  placeholder_passport_name: '例如：WANG/XIAOMING',
  label_passport_expiry: '護照效期區間',
  placeholder_start: '起始日',
  placeholder_end: '結束日',
  section_vip_source: 'VIP 與來源',
  label_vip: 'VIP 狀態',
  label_vip_level: 'VIP 等級',
  label_source: '來源',
  option_all: '全部',
  option_vip: 'VIP',
  option_non_vip: '非 VIP',
  option_bronze: '銅卡',
  option_silver: '銀卡',
  option_gold: '金卡',
  option_platinum: '白金卡',
  option_website: '官網',
  option_referral: '推薦',
  option_phone: '電話',
  option_walk_in: '現場',
  option_other: '其他',
  btn_close: '關閉',
  btn_reset: '重置',
  btn_search: '搜尋',
}

export const COMPANY_LABELS = {
  page_title: '企業客戶管理',
  btn_add: '新增企業客戶',
  search_placeholder: '搜尋企業名稱、統編或聯絡資訊...',
  dialog_title_add: '新增企業客戶',
  dialog_title_edit: '編輯企業客戶',
  dialog_subtitle_add: '新增企業客戶資料',
  dialog_subtitle_edit: (name: string) => `編輯 ${name}`,
  btn_save: '儲存',
  btn_submit_add: '新增',
  alert_enter_name: '請輸入企業名稱',
  section_basic: '基本資訊',
  label_company_name: '企業名稱',
  placeholder_company_name: '請輸入企業名稱',
  label_tax_id: '統一編號',
  label_vip_level: 'VIP 等級',
  option_normal: '普通客戶',
  label_phone: '聯絡電話',
  label_website: '網站',
  section_payment: '付款資訊',
  label_payment_method: '付款方式',
  label_payment_terms: '付款期限',
  label_credit_limit: '信用額度 (NT$)',
  section_invoice: '發票資訊',
  label_invoice_title: '發票抬頭',
  placeholder_invoice_title: '請輸入發票抬頭',
  label_invoice_address: '發票地址',
  placeholder_invoice_address: '請輸入發票地址',
  label_invoice_email: '發票 Email',
  label_notes: '備註',
  placeholder_notes: '其他備註資訊...',
  // detail
  section_bank: '銀行資訊',
  label_bank_name: '銀行名稱',
  label_bank_branch: '分行名稱',
  label_bank_account: '銀行帳號',
  section_address: '地址資訊',
  label_registered_address: '登記地址',
  label_mailing_address: '通訊地址',
  payment_immediate: '即付',
  payment_days: (days: number) => `${days} 天`,
  btn_close: '關閉',
  btn_edit: '編輯',
  title_edit_action: '編輯企業',
  title_delete_action: '刪除企業',
  // table columns
  col_company_name: '企業名稱',
  col_vip_level: 'VIP 等級',
  col_phone: '聯絡電話',
  col_email: 'Email',
  col_payment_terms: '付款條件',
  col_credit_limit: '信用額度',
  col_created_at: '建立日期',
  col_actions: '操作',
  // alerts
  alert_update_success: '企業客戶更新成功',
  alert_update_failed: '更新企業客戶失敗',
  alert_create_success: '企業客戶新增成功',
  alert_create_failed: '新增企業客戶失敗',
  alert_delete_success: '企業客戶刪除成功',
  alert_delete_failed: '刪除企業客戶失敗',
  alert_invalid_email: 'Email 格式不正確',
  alert_invalid_phone: '電話格式不正確（台灣手機或市話）',
  confirm_delete_title: '刪除企業客戶',
  confirm_delete_btn: '確定刪除',
  confirm_delete_with_contacts: (count: number, names: string, companyName: string) =>
    `此企業有 ${count} 位關聯的聯絡人（${names}），刪除企業將同時刪除這些聯絡人。\n\n確定要刪除企業「${companyName}」嗎？`,
  confirm_delete_simple: (name: string) => `確定要刪除企業「${name}」嗎？`,
}
