export const RESET_DB_LABELS = {
  LABEL_4817: '徹底清空本地資料庫，並從 Supabase 重新同步所有資料',
  LABEL_6622: '這個工具會：',
  DELETE_8975: '刪除本地 IndexedDB 的所有資料',
  LABEL_6968: '重新整理頁面後，系統會自動重建資料庫結構',
  LABEL_2869: '從 Supabase 雲端重新下載所有資料',
  LABEL_6918: '將清空以下資料庫',
  LABEL_1215: '重新整理頁面',
  LABEL_6860: '為什麼需要這個工具？',
  LABEL_5751: '問題：',
  LABEL_8168: '當 IndexedDB 的表格結構與代碼定義不一致時，',
  NOT_FOUND_9170: '可能導致資料讀取失敗（例如「目前沒有資料」但 Supabase 有資料）。',
  LABEL_7651: '原因：',
  ADD_2547: '資料庫版本升級機制只會新增缺少的表格，',
  LABEL_995: '但如果舊表格的索引結構已經改變，就會出現不一致。',
  LABEL_3533: '解決方案：',
  LABEL_9350: '確保所有 46 個表格結構都正確。',
  TITLE: 'IndexedDB 重置工具',
  WARNING_DATA_LOSS: '⚠️ 注意：所有未同步到 Supabase 的資料將會遺失！',
  CURRENT_USE: '✓ 當前使用',
  OLD_DB: '(舊資料庫)',
  REBUILD_VERSION: '重建後版本：',
  REBUILD_VERSION_VALUE: 'v6 (46 個表格)',
  CLEARING: '清空中...',
  CLEAR_INDEXEDDB: '清空 IndexedDB',
}
