export const RESET_DB_LABELS = {
  LABEL_4817: '徹底清空本地資料庫，並從 Supabase 重新同步所有資料',
  LABEL_6622: '這個工具會：',
  DELETE_8975: '刪除本地 IndexedDB 的所有資料',
  LABEL_6968: '重新整理頁面後，系統會自動重建資料庫結構',
  LABEL_2869: '從 Supabase 雲端重新下載所有資料',
  LABEL_6918: '將清空以下資料庫',
  LABEL_1215: '重新整理頁面',
  LABEL_6860: '為什麼需要這個工具？',
  LABEL_5751: '問題：',
  LABEL_8168: '當 IndexedDB 的表格結構與代碼定義不一致時，',
  NOT_FOUND_9170: '可能導致資料讀取失敗（例如「目前沒有資料」但 Supabase 有資料）。',
  LABEL_7651: '原因：',
  ADD_2547: '資料庫版本升級機制只會新增缺少的表格，',
  LABEL_995: '但如果舊表格的索引結構已經改變，就會出現不一致。',
  LABEL_3533: '解決方案：',
  LABEL_9350: '確保所有 46 個表格結構都正確。',
  TITLE: 'IndexedDB 重置工具',
  WARNING_DATA_LOSS: '⚠️ 注意：所有未同步到 Supabase 的資料將會遺失！',
  CURRENT_USE: '✓ 當前使用',
  OLD_DB: '(舊資料庫)',
  REBUILD_VERSION: '重建後版本：',
  REBUILD_VERSION_VALUE: 'v6 (46 個表格)',
  CLEARING: '清空中...',
  CLEAR_INDEXEDDB: '清空 IndexedDB',

  // Process messages
  DB_LOCKED: (dbName: string) => `${dbName} 被其他連線鎖定`,
  STEP_1: '步驟 1/4: 正在關閉所有資料庫連線...',
  STEP_2: '步驟 2/4: 等待連線完全關閉...',
  STEP_3: '步驟 3/4: 正在刪除舊資料庫 (venturo-db)...',
  STEP_4: '步驟 4/4: 正在刪除當前資料庫 (VenturoOfflineDB)...',
  SUCCESS: '✅ 所有資料庫已清空！請點擊下方按鈕重新整理頁面。',
  TIMEOUT: '⏱️ 清空超時！請嘗試以下步驟：\n1. 完全關閉瀏覽器\n2. 重新開啟瀏覽器\n3. 只開這個頁面再試一次',
  LOCKED_LABEL: '鎖定',
  LOCKED_MSG: '⚠️ 資料庫被鎖定！請完全關閉瀏覽器（包括所有分頁），然後重新開啟再試。',
  EXEC_FAILED: '❌ 執行失敗：',
}
