export const ACCOUNTING_REPORT_LABELS = {
  // Shared
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_ACCOUNTING: '會計',
  EXPORT_CSV: '匯出 CSV',
  END_DATE: '截止日期',
  SELECT_DATE: '選擇日期',
  QUERY: '查詢',
  TOTAL: '合計',

  // Account types
  TYPE_ASSET: '資產',
  TYPE_LIABILITY: '負債',
  TYPE_REVENUE: '收入',
  TYPE_EXPENSE: '費用',
  TYPE_COST: '成本',

  // Trial Balance
  TB_TITLE: '試算表',
  TB_COL_CODE: '科目代碼',
  TB_COL_NAME: '科目名稱',
  TB_COL_TYPE: '類型',
  TB_COL_DEBIT_AMOUNT: '借方發生額',
  TB_COL_CREDIT_AMOUNT: '貸方發生額',
  TB_COL_DEBIT_BALANCE: '借方餘額',
  TB_COL_CREDIT_BALANCE: '貸方餘額',
  TB_BALANCED: '借貸平衡',
  TB_UNBALANCED: '借貸不平衡',
  TB_BALANCE_TOTAL: '餘額合計',
  TB_EMPTY: '請選擇截止日期並點擊查詢',

  // General Ledger
  GL_TITLE: '總帳報表',
  GL_COL_DATE: '日期',
  GL_COL_VOUCHER: '傳票號',
  GL_COL_SUMMARY: '摘要',
  GL_COL_DEBIT: '借方',
  GL_COL_CREDIT: '貸方',
  GL_COL_BALANCE: '餘額',
  GL_START_DATE: '開始日期',
  GL_EMPTY: '請選擇日期範圍並點擊查詢',
  GL_OPENING_BALANCE: '期初餘額',
  GL_COL_VOUCHER_NO: '傳票編號',
  GL_COL_ACCOUNT_CODE: '科目代碼',
  GL_COL_ACCOUNT_NAME: '科目名稱',
  GL_COL_ACCOUNT: '科目',
  GL_TO: '至',
  GL_START_DATE_PLACEHOLDER: '開始日期',
  GL_END_DATE_PLACEHOLDER: '結束日期',
  GL_SELECT_ACCOUNT_PLACEHOLDER: '選擇科目（可選）',
  GL_ACCOUNT_LOADING: '載入中...',
  GL_ACCOUNT_NOT_FOUND: '找不到科目',
  GL_DEBIT_TOTAL: '借方合計',
  GL_CREDIT_TOTAL: '貸方合計',
  GL_DIFFERENCE: '差額',

  // Account Ledger
  AL_TITLE: '科目明細帳',
  AL_SELECT_ACCOUNT: '選擇科目 *',
  AL_EMPTY: '請選擇科目並點擊查詢',
  AL_EMPTY_WITH_ACCOUNT: '請點擊查詢按鈕',
  AL_BREADCRUMB_REPORTS: '報表',
  AL_SELECT_ACCOUNT_PLACEHOLDER: '請選擇科目',
  AL_OPENING_BALANCE: '期初餘額',
  AL_CLOSING_BALANCE: '期末餘額',
  AL_PERIOD_TOTAL: '期間合計',
  AL_ACCOUNT_LABEL: '科目',

  // Balance Sheet
  BS_TITLE: '資產負債表',
  BS_ASSETS: '資產',
  BS_LIABILITIES: '負債',
  BS_TOTAL_ASSETS: '資產合計',
  BS_TOTAL_LIABILITIES: '負債合計',
  BS_EMPTY: '請選擇報表日期並點擊查詢',
  BS_REPORT_DATE: '報表日期',
  BS_TOTAL_ASSETS_AMOUNT: '資產總額',
  BS_TOTAL_LIABILITIES_AMOUNT: '負債總額',
  BS_NET_ASSETS: '淨資產（權益）',
  BS_EQUITY: '權益（資產-負債）',
  BS_EQUITY_DISPLAY: '權益（資產 - 負債）',
  BS_NO_ASSET_BALANCE: '無資產科目餘額',
  BS_NO_LIABILITY_BALANCE: '無負債科目餘額',
  BS_NET_ASSETS_SHORT: '淨資產',
  BS_CSV_ITEM: '項目',
  BS_CSV_AMOUNT: '金額',

  // Income Statement
  IS_TITLE: '損益表',
  IS_REVENUE: '收入',
  IS_EXPENSE: '費用',
  IS_COST: '成本',
  IS_TOTAL_REVENUE: '收入合計',
  IS_TOTAL_EXPENSE: '費用合計',
  IS_TOTAL_COST: '成本合計',
  IS_NET_INCOME: '本期損益',
  IS_EMPTY: '請選擇日期範圍並點擊查詢',
  IS_REVENUE_SECTION: '一、營業收入',
  IS_COST_SECTION: '二、營業成本',
  IS_GROSS_PROFIT: '三、營業毛利',
  IS_EXPENSE_SECTION: '四、營業費用',
  IS_OPERATING_INCOME: '五、營業淨利',
  IS_OPERATING_INCOME_LOSS: '五、營業淨利（淨損）',
  IS_REVENUE_TOTAL: '營業收入合計',
  IS_COST_TOTAL: '營業成本合計',
  IS_EXPENSE_TOTAL: '營業費用合計',
  IS_REVENUE_LABEL: '營業收入',
  IS_TOTAL_EXPENDITURE: '總支出',
  IS_CSV_ITEM: '項目',
  IS_CSV_AMOUNT: '金額',
  IS_CSV_RATIO: '佔收入比例',
  IS_START_DATE: '開始日期',
  IS_TO: '至',
  IS_END_DATE: '結束日期',

  // Cash Flow Statement
  CF_TITLE: '現金流量表',
  CF_OPERATING: '營業活動',
  CF_INVESTING: '投資活動',
  CF_FINANCING: '籌資活動',
  CF_NET_INCREASE: '現金淨增加額',
  CF_OPENING_CASH: '期初現金',
  CF_CLOSING_CASH: '期末現金',
  CF_EMPTY: '請選擇日期範圍並點擊查詢',
}
