// 會計模組 UI 標籤常量

export const ACCOUNTS_PAGE_LABELS = {
  page_title: '科目表管理',
  search_placeholder: '搜尋科目代碼或名稱...',
  btn_add: '新增科目',
  col_code: '科目代碼',
  col_name: '科目名稱',
  col_type: '類型',
  col_status: '狀態',
  col_system: '系統科目',
  action_edit: '編輯',
  action_delete: '刪除',
  status_active: '啟用',
  status_inactive: '停用',
  system_yes: '已鎖定',
  confirm_delete_title: '刪除科目',
  toast_deleted: '科目已刪除',
  toast_delete_failed: '刪除失敗',
  error_system_locked: '系統科目不可刪除',
  empty_message: '尚無科目資料',
  type_asset: '資產',
  type_liability: '負債',
  type_equity: '權益',
  type_revenue: '收入',
  type_expense: '費用',
  type_cost: '成本',
}

export const ACCOUNT_DIALOG_LABELS = {
  title_add: '新增科目',
  title_edit: '編輯科目',
  label_code: '科目代碼',
  placeholder_code: '如：1100',
  label_name: '科目名稱',
  placeholder_name: '如：銀行存款',
  label_type: '類型',
  label_description: '說明',
  placeholder_description: '科目說明...',
  label_active: '啟用',
  btn_cancel: '取消',
  btn_save: '儲存',
  btn_saving: '儲存中...',
  toast_created: '科目已新增',
  toast_updated: '科目已更新',
  toast_save_failed: '儲存失敗',
  error_system_locked: '系統科目不可編輯',
  auto_generate: '（自動產生）',
}

export const BANK_ACCOUNTS_PAGE_LABELS = {
  page_title: '銀行帳戶管理',
  search_placeholder: '搜尋帳戶名稱或銀行...',
  btn_add: '新增銀行帳戶',
  col_name: '帳戶名稱',
  col_bank: '銀行名稱',
  col_account_number: '帳號',
  col_status: '狀態',
  action_edit: '編輯',
  action_delete: '刪除',
  status_active: '啟用',
  status_inactive: '停用',
  confirm_delete_title: '刪除銀行帳戶',
  toast_deleted: '銀行帳戶已刪除',
  toast_delete_failed: '刪除失敗',
  empty_message: '尚無銀行帳戶資料',
}

export const BANK_ACCOUNT_DIALOG_LABELS = {
  title_add: '新增銀行帳戶',
  title_edit: '編輯銀行帳戶',
  label_name: '帳戶名稱',
  placeholder_name: '如：合作金庫',
  label_bank: '銀行名稱',
  placeholder_bank: '如：合庫西門分行',
  label_account_number: '帳號',
  placeholder_account_number: '如：0026800123456',
  label_linked_account: '對應會計科目',
  placeholder_linked_account: '選擇科目',
  linked_account_none: '不指定',
  linked_account_hint: '選擇此銀行帳戶對應的會計科目，用於自動過帳',
  label_active: '啟用',
  btn_cancel: '取消',
  btn_save: '儲存',
  btn_saving: '儲存中...',
  toast_created: '銀行帳戶已新增',
  toast_updated: '銀行帳戶已更新',
  toast_save_failed: '儲存失敗',
}

export const VOUCHERS_PAGE_LABELS = {
  page_title: '傳票管理',
  btn_add: '新增傳票',
  col_voucher_no: '傳票編號',
  col_date: '日期',
  col_description: '摘要',
  col_debit: '借方',
  col_credit: '貸方',
  col_status: '狀態',
  col_actions: '操作',
  action_view: '查看',
  action_edit: '編輯',
  action_reverse: '反沖',
  status_draft: '草稿',
  status_posted: '已過帳',
  status_reversed: '已反沖',
  status_locked: '已鎖定',
  empty_message: '尚無傳票資料',
}

export const VOUCHER_FORM_LABELS = {
  title_add: '新增傳票',
  title_edit: '編輯傳票',
  label_date: '日期',
  label_description: '摘要',
  placeholder_description: '傳票摘要說明...',
  label_account: '選擇科目',
  label_debit: '借方',
  label_credit: '貸方',
  label_memo: '說明',
  btn_cancel: '取消',
  btn_save_draft: '儲存草稿',
  btn_post: '過帳',
  btn_saving: '儲存中...',
  btn_posting: '處理中...',
  error_date_required: '請選擇傳票日期',
  error_min_lines: '傳票至少需要 2 筆分錄',
  error_min_valid_lines: '傳票至少需要 2 筆有效分錄',
  error_balance: '借貸金額必須平衡',
  error_user_incomplete: '用戶資訊不完整',
  toast_save_failed: '儲存傳票失敗',
  error_load_lines: '載入分錄失敗:',
  error_save_lines: '儲存傳票失敗:',
}

export const VOUCHER_DETAIL_LABELS = {
  title: '傳票明細',
  label_voucher_no: '傳票編號',
  label_date: '日期',
  label_description: '摘要',
  label_status: '狀態',
  col_line_no: '行號',
  col_account: '科目',
  col_debit: '借方',
  col_credit: '貸方',
  col_memo: '說明',
  status_draft: '草稿',
  status_posted: '已過帳',
  status_reversed: '已反沖',
}

export const REVERSE_VOUCHER_LABELS = {
  title: '確認反沖',
  label_reason: '反沖原因',
  placeholder_reason: '請說明反沖原因...',
  btn_cancel: '取消',
  btn_confirm: '確認反沖',
  btn_processing: '處理中...',
  error_reason_required: '請輸入反沖原因',
  toast_failed: '反沖失敗',
  error_user_incomplete: '用戶資訊不完整',
  info_target_voucher: '即將反沖以下傳票：',
  warning_irreversible: '⚠️ 反沖後將產生一張新的反向傳票，原傳票狀態將變更為「已反沖」。此操作無法復原。',
}

export const VOUCHER_DETAIL_LABELS_EXT = {
  status_locked: '已鎖定',
  loading_text: '載入中...',
  no_data_text: '無分錄資料',
  total_label: '合計',
  imbalance_warning: '⚠️ 借貸不平衡！差額：',
}

export const VOUCHER_FORM_LABELS_EXT = {
  label_voucher_date: '傳票日期',
  label_voucher_no: '傳票編號',
  label_memo: '摘要',
  label_entry_details: '分錄明細',
  btn_add_line: '新增行',
  col_line_no: '#',
  col_account: '科目',
  col_memo: '摘要',
  col_debit: '借方',
  col_credit: '貸方',
  total_label: '合計',
  imbalance_warning: '⚠️ 借貸不平衡！差額：',
  balanced_message: '✓ 借貸已平衡',
  btn_cancel: '取消',
  btn_save_draft: '儲存草稿',
  btn_post: '過帳',
  title_add: '新增傳票',
  title_edit: '編輯傳票',
}

// 動態消息生成函數
export const CONFIRMATION_MESSAGES = {
  deleteAccount: (code: string, name: string) => `確定要刪除科目「${code} ${name}」嗎？`,
  deleteBankAccount: (name: string) => `確定要刪除「${name}」嗎？`,
}

export const SUCCESS_MESSAGES = {
  reverseSuccess: (voucherNo: string) => `反沖成功，新傳票編號：${voucherNo}`,
  saveVoucherDraft: (voucherNo: string) => `傳票 ${voucherNo} 已儲存為草稿`,
  saveVoucherPosted: (voucherNo: string) => `傳票 ${voucherNo} 已過帳`,
}

export const CALCULATION_MESSAGES = {
  imbalanceAmount: (amount: number) => `${amount.toLocaleString()}`,

  LABEL_4298: '傳票摘要說明...',
  SELECT_3: '選擇科目',
  LABEL_5591: '說明',
}
export const ACCOUNTING_LABELS = {
  MANAGE_6235: '帳戶管理',
  TOTAL_9058: '總資產',
  NOT_FOUND_1446: '還沒有帳戶',
  ADD_3126: '新增第一個帳戶',
  LABEL_3476: '可用額度',
  ADD_236: '新增帳戶',

  LABEL_7125: '帳戶類型',
  LABEL_1477: '帳戶名稱',
  PLEASE_ENTER_247: '信用卡請輸入負數（如：-5000 表示欠款5000元）',
  LABEL_1690: '信用額度',
  TOTAL_9749: '設定這張信用卡的總額度限制',
  LABEL_3288: '顏色標識',
  LABEL_9909: '備註說明',
  LABEL_9373: '輸入帳戶備註（選填）',
  PREVIEW_1832: '預覽效果',

  SELECT_2544: '選擇交易類型',
  BACK: '返回',
  NOT_FOUND_7772: '還沒有分類',
  ADD_7344: '新增第一個分類',
  LABEL_5271: '分類名稱',
  EXAMPLE_9015: '例如：餐費、交通、娛樂',
  CANCEL: '取消',
  ADD: '新增',
  ADD_8245: '新增分類',
  ADD_3016: '新增記帳',
  LABEL_2477: '更改分類',
  SELECT_6666: '選擇帳戶',
  PLEASE_SELECT_6196: '請選擇帳戶',
  AMOUNT: '金額',
  DATE: '日期',
  SELECT_5234: '選擇日期',
  REMARKS: '備註',
  LABEL_3027: '輸入備註（選填）',
  SELECT_CATEGORY_PREFIX: '選擇',
  EXPENSE_CATEGORY: '支出',
  INCOME_CATEGORY: '收入',
  CATEGORY_SUFFIX: '分類',
}
