export const TRANSPORTATION_RATES_LABELS = {
  PAGE_TITLE: '車資管理',
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_DATABASE: '資料庫管理',
  BREADCRUMB_RATES: '車資管理',
  ADD_COUNTRY: '新增國家',
  ADD_COUNTRY_DIALOG_TITLE: '新增國家',
  COUNTRY_NAME_LABEL: '國家名稱',
  COUNTRY_NAME_PLACEHOLDER: '例如：越南、泰國',
  CANCEL: '取消',
}
