// 人資模組 UI 標籤常量

export const ATTENDANCE_PAGE_LABELS = {
  page_title: '出勤紀錄',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_attendance: '出勤紀錄',
  placeholder_start_date: '開始日期',
  range_separator: '至',
  placeholder_end_date: '結束日期',
  all_employees: '全部員工',
  unknown_employee: '未知',
  col_date: '日期',
  col_employee: '員工',
  col_clock_in: '上班時間',
  col_clock_out: '下班時間',
  col_work_hours: '工時',
  col_overtime: '加班',
  col_status: '狀態',
  col_notes: '備註',
  action_edit: '編輯',
  action_delete: '刪除',
  summary_total_days: '總天數',
  summary_present: '正常',
  summary_late: '遲到',
  summary_absent: '缺勤',
  summary_total_hours: '總工時',
  summary_total_overtime: '總加班',
  empty_message: '尚無出勤紀錄',
  dialog_title_add: '新增出勤紀錄',
  dialog_title_edit: '編輯出勤紀錄',
  label_employee: '員工',
  label_date: '日期',
  label_clock_in: '上班時間',
  label_clock_out: '下班時間',
  label_status: '狀態',
  label_notes: '備註',
  placeholder_employee: '選擇員工',
  placeholder_date: '選擇日期',
  placeholder_notes: '備註說明',
  btn_cancel: '取消',
  btn_update: '更新',
  btn_add: '新增',
  confirm_delete_title: '刪除出勤紀錄',
  confirm_delete_message: (name: string | undefined, date: string) =>
    `確定要刪除 ${name} 於 ${date} 的出勤紀錄嗎？`,
  toast_deleted: '出勤紀錄已刪除',
  toast_updated: '出勤紀錄已更新',
  toast_created: '出勤紀錄已新增',
  error_required: '請選擇員工和日期',
}

export const PAYROLL_PAGE_LABELS = {
  page_title: '薪資管理',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_payroll: '薪資管理',
  year_suffix: '年',
  month_suffix: '月',
  col_period: '期間',
  col_date_range: '日期範圍',
  col_status: '狀態',
  col_confirmed_at: '確認時間',
  btn_view: '查看',
  btn_calculate: '計算',
  btn_confirm: '確認',
  btn_mark_paid: '發放',
  empty_message: '尚無薪資期間',
  dialog_create_title: '建立薪資期間',
  label_year: '年度',
  label_month: '月份',
  btn_cancel: '取消',
  btn_create: '建立',
  toast_period_created: '薪資期間已建立',
  confirm_calculate_message: (year: number, month: number) =>
    `確定要計算 ${year}年${month}月 的薪資嗎？此操作會覆蓋現有的薪資紀錄。`,
  confirm_calculate_title: '計算薪資',
  toast_calculated: '薪資計算完成',
  confirm_confirm_message: (year: number, month: number) =>
    `確定要確認 ${year}年${month}月 的薪資嗎？確認後將無法修改。`,
  confirm_confirm_title: '確認薪資',
  toast_confirmed: '薪資已確認',
  confirm_paid_message: (year: number, month: number) =>
    `確定要標記 ${year}年${month}月 的薪資為已發放嗎？`,
  confirm_paid_title: '標記發放',
  toast_paid: '已標記為發放',
  records_dialog_title: (year: number, month: number) =>
    `${year}年${month}月 薪資明細`,
  records_dialog_title_default: '薪資明細',
  summary_employees: '員工數',
  summary_gross: '應發總額',
  summary_net: '實發總額',
  summary_overtime: '加班費',
  summary_deductions: '扣款',
  empty_records: '尚無薪資紀錄，請先計算薪資',
  col_employee: '員工',
  col_base_salary: '底薪',
  col_overtime_pay: '加班費',
  col_bonus: '獎金',
  col_deductions_label: '扣款',
  col_gross: '應發',
  col_net: '實發',
  action_payslip: '薪資單',
  payslip_title: '薪資單',
  payslip_print_title: (name: string | undefined) => `薪資單 - ${name}`,
  payslip_employee_name: '員工姓名：',
  payslip_period: '薪資期間：',
  payslip_col_item: '項目',
  payslip_col_amount: '金額',
  payslip_base_salary: '底薪',
  payslip_overtime: (hours: string) => `加班費（${hours} 小時）`,
  payslip_bonus: '獎金',
  payslip_allowances: '津貼',
  payslip_other_additions: '其他加項',
  payslip_gross: '應發薪資',
  payslip_unpaid_leave: (days: number) => `無薪假扣款（${days} 天）`,
  payslip_other_deductions: '其他扣款',
  payslip_net: '實發薪資',
  payslip_work_days: (actual: number, total: number) =>
    `出勤天數：${actual} / ${total} 天`,
  payslip_paid_leave: (days: number) => `有薪假天數：${days} 天`,
  payslip_unpaid_leave_days: (days: number) => `無薪假天數：${days} 天`,
  btn_print: '列印',
}

export const LEAVE_PAGE_LABELS = {
  page_title: '請假管理',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_leave: '請假管理',
  tab_requests: '請假申請',
  tab_types: '假別設定',
  status_pending: '待審核',
  status_approved: '已核准',
  status_rejected: '已駁回',
  status_cancelled: '已取消',
  col_code: '代碼',
  col_type_name: '假別名稱',
  col_days_per_year: '年度配額',
  col_is_paid: '給薪',
  col_requires_proof: '需證明',
  col_is_active: '狀態',
  days_suffix: '天',
  days_unlimited: '無限制',
  yes: '是',
  no: '否',
  active: '啟用',
  inactive: '停用',
  action_edit: '編輯',
  action_delete: '刪除',
  col_employee: '員工',
  col_leave_type: '假別',
  col_start_date: '開始日期',
  col_end_date: '結束日期',
  col_days: '天數',
  col_status: '狀態',
  col_applied_at: '申請時間',
  btn_approve: '准',
  btn_reject: '駁',
  empty_requests: '尚無請假申請',
  init_hint: '尚未設定假別類型，建議初始化預設假別',
  btn_init: '初始化',
  confirm_init: '確定要初始化預設假別類型嗎？',
  confirm_init_title: '初始化假別',
  toast_initialized: '已成功初始化預設假別類型',
  confirm_delete_message: (name: string) => `確定要刪除「${name}」假別嗎？`,
  confirm_delete_title: '刪除假別',
  toast_type_deleted: '假別已刪除',
  confirm_approve_message: (name: string | undefined, type: string | undefined, start: string, end: string, days: number) =>
    `確定要核准「${name}」的請假申請嗎？\n\n假別：${type}\n期間：${start} ~ ${end}\n天數：${days} 天`,
  confirm_approve_title: '核准請假',
  toast_approved: '已核准請假申請',
  reject_dialog_title: '駁回請假申請',
  reject_label: '駁回原因',
  reject_placeholder: '請輸入駁回原因...',
  error_reject_reason: '請填寫駁回原因',
  toast_rejected: '已駁回請假申請',
  btn_cancel: '取消',
  btn_reject_confirm: '確認駁回',
  type_section_title: '假別類型',
  dialog_title_add: '新增假別',
  dialog_title_edit: '編輯假別',
  label_type_name: '假別名稱',
  placeholder_type_name: '如：特休',
  label_code: '代碼',
  placeholder_code: '如：ANNUAL',
  label_days_per_year: '年度配額（天）',
  placeholder_days: '留空表示無限制',
  checkbox_paid: '給薪假',
  checkbox_proof: '需要證明文件',
  checkbox_active: '啟用',
  btn_update: '更新',
  btn_add: '新增',
  error_required: '請填寫假別名稱和代碼',
  toast_type_updated: '假別已更新',
  toast_type_created: '假別已新增',
}
