export const SUPPLIER_LABELS = {
  MANAGE_5809: '派單管理',
  LABEL_7626: '狀態：',
  ALL: '全部',
  LABEL_444: '待派單',
  LABEL_4291: '已派單',
  LABEL_7255: '已完成',
  LABEL_8625: '指派司機',
  LABEL_2651: '將此需求派給司機執行',
  SELECT_5145: '選擇司機',
  PLEASE_SELECT_2927: '請選擇司機',
  ADD_9655: '尚未建立司機資料，請先到車隊管理新增司機',
  CANCEL: '取消',

  LABEL_8192: '財務報表',
  LABEL_4658: '本月',
  LABEL_4990: '上月',
  LABEL_9090: '近三個月',
  EXPORT_5502: '匯出報表',
  TOTAL_1389: '總營收',
  LABEL_2454: '待請款',
  LABEL_5100: '已收款',
  LABEL_7764: '收款率',
  LABEL_9799: '請款明細',
  LOADING_6912: '載入中...',
  NOT_FOUND_6711: '目前沒有請款記錄',
  LABEL_6153: '服務日期',
  LABEL_9750: '團號',
  LABEL_4272: '團名',
  AMOUNT: '金額',
  STATUS: '狀態',

  LABEL_174: '需求收件匣',

  LABEL_8868: '需求資訊',
  LABEL_9868: '日期：',
  LABEL_4600: '數量：',
  LABEL_5457: '說明：',
  LABEL_6418: '車牌號碼',
  EXAMPLE_2914: '例如：ABC-1234',
  LABEL_6947: '司機姓名',
  LABEL_5402: '輸入司機姓名',
  LABEL_8624: '輸入電話號碼',
  LABEL_915: '可用開始日期',
  LABEL_7036: '可用結束日期',
  LABEL_3404: '報價金額',
  LABEL_2285: '輸入金額',
  REMARKS: '備註',
  LABEL_8253: '選填備註',
  LABEL_7829: '回覆備註',
  LABEL_694: '其他說明或備註...',
  LABEL_9: '送出回覆',

  // SupplierDispatchPage hardcoded strings
  DISPATCH_PENDING: '待派單',
  DISPATCH_ASSIGNED: '已派單',
  DISPATCH_COMPLETED: '已完成',
  COL_SERVICE_DATE: '服務日期',
  COL_TOUR_CODE: '團號',
  COL_SERVICE_CONTENT: '服務內容',
  COL_QUANTITY: '數量',
  COL_DISPATCH_STATUS: '派單狀態',
  COL_ASSIGNED_DRIVER: '指派司機',
  COL_ACTIONS: '操作',
  UNIT_VEHICLE: '台',
  TOTAL_REQUESTS: (count: number) => `共 ${count} 筆需求`,
  EMPTY_DISPATCH: '目前沒有需要派單的需求',
  TOUR_CODE_LABEL: '團號：',
  ASSIGNING: '派單中...',
  CONFIRM_ASSIGN: '確認派單',
  ASSIGN_FAILED: '派單失敗，請稍後再試',
  BTN_ASSIGN: '派單',
  BTN_MODIFY: '修改',

  // SupplierResponseDialog hardcoded strings
  RESOURCE_VEHICLE: '車輛',
  RESOURCE_LEADER: '領隊',
  VIEW_RESPONSE: '查看回覆',
  RESPOND_REQUEST: '回覆需求',
  VEHICLE_NAME_LABEL: '車輛名稱/車型',
  LEADER_NAME_LABEL: '領隊姓名',
  VEHICLE_NAME_PLACEHOLDER: '例如：Toyota Coaster 中巴',
  LEADER_NAME_PLACEHOLDER: '例如：王小明',
  RESOURCE_INFO: (type: string, count: number) => `${type}資訊 (${count})`,
  ADD_RESOURCE: (type: string) => `新增${type}`,
  RESOURCE_INDEX: (type: string, index: number) => `${type} #${index}`,
  DRIVER_PHONE: '司機電話',
  LEADER_PHONE: '領隊電話',
  FILL_AT_LEAST_ONE: (type: string) => `請至少填寫一個${type}資訊`,
  RESPONSE_SUBMITTED: '回覆已送出',
  SUBMIT_FAILED: '送出失敗',
  BTN_CLOSE: '關閉',
  BTN_CANCEL: '取消',

  // SupplierRequestsPage hardcoded strings
  STATUS_PENDING_REPLY: '待回覆',
  STATUS_RESPONDED: '已回覆',
  STATUS_QUOTED: '已報價',
  STATUS_ACCEPTED: '已確認',
  STATUS_REJECTED: '已拒絕',
  STATUS_NEED_INFO: '待補資料',
  CAT_TRANSPORT: '交通（派車）',
  CAT_GUIDE: '領隊',
  CAT_HOTEL: '住宿',
  CAT_RESTAURANT: '餐食',
  CAT_ACTIVITY: '門票/活動',
  CAT_OTHER: '其他',
  COL_STATUS: '狀態',
  COL_CATEGORY: '類別',
  COL_TOUR_NAME: '團名/專案',
  COL_SERVICE_DATE_REQ: '服務日期',
  COL_QUANTITY_REQ: '數量',
  COL_RECEIVED_AT: '收到時間',
  UNNAMED: '未命名',
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_SUPPLIER: '供應商首頁',
  BREADCRUMB_REQUESTS: '需求收件匣',
  TAB_ALL: '全部',
  TAB_PENDING: '待回覆',
  TAB_QUOTED: '已報價',
  TAB_ACCEPTED: '已確認',
  TAB_REJECTED: '已拒絕',
  BTN_RESPOND: '回覆',
  BTN_VIEW: '查看',

  // SupplierFinancePage hardcoded strings
  TASK_COUNT: (count: number) => `共 ${count} 筆任務`,
  STATUS_PAID: '已收款',
  STATUS_PENDING_CLAIM: '待請款',
}
