export const ESIMS_LABELS = {
  PAGE_TITLE: '網卡管理',
  SEARCH_PLACEHOLDER: '搜尋網卡單號、團號、訂單編號...',
  ADVANCED_SEARCH: '詳細搜尋',
  ADD_ESIM: '新增網卡',
  COL_ESIM_NUMBER: '網卡單號',
  COL_TOUR_NAME: '團名',
  COL_ORDER_NUMBER: '訂單編號',
  COL_PRODUCT_ID: '商品ID',
  COL_QUANTITY: '數量',
  COL_UNIT_PRICE: '單價',
  COL_TOTAL: '總金額',
  COL_SUPPLIER_ORDER: '供應商訂單號',
  COL_STATUS: '狀態',
  COL_ACTIONS: '操作',
  ACTION_EDIT: '編輯',
  ACTION_DELETE: '刪除',
  QUANTITY_UNIT: '張',
  CONFIRM_DELETE: '確定要刪除此網卡嗎？',
  DELETE_TITLE: '刪除網卡',
  DELETE_FAILED: '刪除失敗，請稍後再試',
}
