// Finance module labels
export const FinanceLabels = {
  // Travel Invoice Create Page
  invoiceCreateTitle: '開立新發票',
  basicInfo: '基本資訊',
  issueDate: '開立日期',
  selectDate: '選擇日期',
  taxType: '課稅別',
  selectTaxType: '選擇課稅別',
  dutiable: '應稅',
  zeroRate: '零稅率',
  taxFree: '免稅',
  reportStatus: '申報註記',
  unreported: '未申報',
  reported: '已申報',
  buyerInfo: '買受人資訊',
  buyerName: '買受人名稱',
  buyerNameRequired: '買受人名稱 *',
  enterBuyerName: '請輸入買受人名稱',
  unifiedBusinessNumber: '統一編號',
  ubnPlaceholder: '8 碼數字',
  email: 'Email',
  emailForReceipt: '用於寄送電子收據',
  mobileNumber: '手機號碼',
  mobilePlaceholder: '09xxxxxxxx',
  productDetails: '商品明細',
  summary: '摘要',
  quantity: '數量',
  unitPrice: '單價',
  unit: '單位',
  amount: '金額',
  handle: '處理',
  productName: '商品名稱',
  addRow: '新增一列',
  remarks: '備註',
  remarksPlaceholder: '請輸入備註（限 50 字）',
  remarksNote: '可輸入大小寫英文、中文（限 50 字，不可輸入符號，例如：/ , - = 等）',
  total: '總計',
  cancel: '取消',
  issuing: '開立中...',
  issueInvoice: '開立發票',
  enterBuyerNameError: '請輸入買受人名稱',
  completeProductInfoError: '請完整填寫商品資訊',
  unknownError: '發生未知錯誤',

  // Payments Page
  paymentManagement: '收款管理',
  searchReceiptPlaceholder: '搜尋收款單號、訂單編號、團名...',
  exportExcel: '匯出 Excel',
  batchConfirm: '批量確認',
  batchPayment: '批量收款',
  addPayment: '新增收款',
  receiptNumber: '收款單號',
  receiptDate: '收款日期',
  orderNumber: '訂單編號',
  tourName: '團名',
  receiptAmount: '應收金額',
  actualAmount: '實收金額',
  status: '狀態',
  actions: '操作',
  edit: '編輯',
  createReceiptFailedPrefix: '建立收款單失敗',
  createReceiptFailedTitle: '建立收款單失敗'
}