-- Migration: 禁用 RLS（内部管理系统）
-- Date: 2025-10-29
-- 说明: 这是一个内部管理系统，所有已认证用户都应该能访问所有数据

BEGIN;

-- ==========================================
-- 禁用所有主要表的 RLS
-- ==========================================

-- 1. suppliers 表
ALTER TABLE public.suppliers DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_authenticated_all" ON public.suppliers;

-- 2. itineraries 表
ALTER TABLE public.itineraries DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "allow_authenticated_all" ON public.itineraries;

-- 3. 其他核心表（预防性禁用）
ALTER TABLE IF EXISTS public.tours DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.visas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payment_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.disbursement_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.receipt_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quote_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_addons DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.calendar_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.regions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workspaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channel_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bulletins DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workspace_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.timebox_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.advance_lists DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shared_order_lists DISABLE ROW LEVEL SECURITY;

COMMIT;
