-- 禁用所有表格的 RLS (Row Level Security)
-- Venturo 是內部管理系統，所有已認證用戶都應該能訪問所有數據

BEGIN;

-- 核心業務表
ALTER TABLE IF EXISTS public.todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.calendar_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tours DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.itineraries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payment_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.invoices DISABLE ROW LEVEL SECURITY;

-- 資料庫管理表
ALTER TABLE IF EXISTS public.countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.regions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.attractions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hotels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.restaurants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.shops DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.visas DISABLE ROW LEVEL SECURITY;

-- HR 表
ALTER TABLE IF EXISTS public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_roles DISABLE ROW LEVEL SECURITY;

-- Workspace/通訊表
ALTER TABLE IF EXISTS public.workspaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channel_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channel_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.message_reads DISABLE ROW LEVEL SECURITY;

-- 範本表
ALTER TABLE IF EXISTS public.itinerary_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.itinerary_template_days DISABLE ROW LEVEL SECURITY;

-- 財務表
ALTER TABLE IF EXISTS public.disbursements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.receipts DISABLE ROW LEVEL SECURITY;

-- 其他表
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.timebox_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.manifestation_items DISABLE ROW LEVEL SECURITY;

COMMIT;

COMMENT ON SCHEMA public IS 'Venturo 內部管理系統 - 所有表格已禁用 RLS，使用 Supabase Auth 控制登入權限';
