export const LABELS = {
  // EsimCreateDialog
  batchCreateTitle: '批次新增網卡',
  selectTourCode: '選擇團號',
  autoSelectEsimTour: '(自動選擇網卡專用團)',
  selectTourCodePlaceholder: '選擇團號...',
  orderNumber: '訂單',
  orderAutoCreate: '(選填，未選擇將自動建立)',
  orderPlaceholder: (hasTour: boolean) => hasTour ? '請選擇訂單或留空自動建立' : '請先選擇團號',
  addOrder: '+ 新增訂單',
  contactPerson: '聯絡人',
  contactPersonPlaceholder: '請輸入聯絡人',
  contactPhone: '聯絡電話',
  contactPhonePlaceholder: '請輸入聯絡電話',
  productRegion: '產品地區',
  selectProduct: '選擇產品...',
  receiveEmail: '接收信箱',
  notePlaceholder: '備註',
  quantitySuffix: '張',

  // EsimSearchDialog
  detailedSearch: '詳細搜尋',
  esimNumber: '網卡單號',
  esimNumberPlaceholder: '輸入網卡單號',
  tourCode: '團號',
  tourCodePlaceholder: '輸入團號',
  orderNumberLabel: '訂單編號',
  orderNumberPlaceholder: '輸入訂單編號',
  supplierOrderNumber: '供應商訂單編號',
  supplierOrderNumberPlaceholder: '輸入供應商訂單編號',
  productId: '商品ID',
  productIdPlaceholder: '輸入商品ID',
  email: '信箱',
  emailPlaceholder: '輸入信箱',
  status: '狀態',
  statusPlaceholder: '選擇狀態',
  reset: '重置',
  search: '搜尋',

  CONFIRM_7150: '待確認',
  CONFIRM_469: '已確認',
  LABEL_8594: '錯誤',
}
