export const LABELS = {
  // Header and Navigation
  SYSTEM_SETTINGS: '系統設定',
  HOME: '首頁',
  SETTINGS: '設定',
  USER: '使用者',
  LOGOUT: '登出',
  
  // Setup Mode
  WELCOME_TITLE: '歡迎！請完成帳號設定',
  FIRST_LOGIN_DESC: '這是您首次登入系統，請完成以下設定以確保帳號安全：',
  CHANGE_PASSWORD_TITLE: '1. 修改密碼',
  CHANGE_PASSWORD_DESC: '請將預設密碼改為您自己的密碼',
  UPLOAD_AVATAR_TITLE: '2. 上傳頭像',
  UPLOAD_AVATAR_DESC: '上傳您的照片，方便同事辨認',
  SKIP_LATER: '稍後再說',
  
  // Workspaces Page
  WORKSPACE_MANAGEMENT: '工作空間管理',
  WORKSPACE_MANAGEMENT_DESC: '管理多分公司設定，實現資料隔離（台北公司 vs 台中分公司）',
  ADD_WORKSPACE: '新增工作空間',
  DATA_ISOLATION_TITLE: '什麼是資料隔離？',
  DATA_ISOLATION_DESC: '工作空間可以確保不同分公司的資料獨立管理：',
  DATA_ISOLATION_POINT1: '• 台北員工預設看到台北的旅遊團、訂單、客戶',
  DATA_ISOLATION_POINT2: '• 台中員工預設看到台中的旅遊團、訂單、客戶',
  DATA_ISOLATION_POINT3: '• 系統管理員可以切換工作空間查看所有資料',
  DATA_ISOLATION_POINT4: '• 員工資料、航空公司、飯店等主檔仍然全公司共享',
  NO_DESCRIPTION: '無描述',
  STATUS_ACTIVE: '啟用',
  STATUS_INACTIVE: '停用',
  EMPLOYEE_COUNT: '員工數：{count} 人',
  EDIT: '編輯',
  EDIT_FEATURE_COMING: '編輯功能開發中',
  
  // Workspace Creation Dialog
  ADD_WORKSPACE_TITLE: '新增工作空間',
  WORKSPACE_NAME_LABEL: '名稱',
  WORKSPACE_NAME_REQUIRED: '*',
  WORKSPACE_NAME_PLACEHOLDER: '例如：台北總公司、台中分公司',
  WORKSPACE_DESCRIPTION_LABEL: '說明',
  WORKSPACE_DESCRIPTION_PLACEHOLDER: '簡短說明此工作空間',
  CANCEL: '取消',
  CREATE: '建立',
  
  // Messages and Notifications
  WORKSPACE_NAME_REQUIRED_MSG: '請填寫工作空間名稱',
  ANNOUNCEMENT: '公告',
  ANNOUNCEMENT_CHANNEL_DESC: '此頻道用於發布全工作空間的重要公告。',
  BOT_CREATION_FAILED: '建立機器人失敗（不影響 workspace 建立）',
  WORKSPACE_CREATED_SUCCESS: '工作空間、公告頻道和機器人已建立',
  CREATION_FAILED: '建立失敗',
  
  // Empty State
  NO_WORKSPACE_TITLE: '尚未建立工作空間',
  NO_WORKSPACE_DESC: '開始建立第一個工作空間以啟用多分公司管理',
  
  // Account Settings
  ACCOUNT_SECURITY: '帳號安全',
  AVATAR: '頭像',
  PERSONAL_AVATAR: '個人頭像',
  CLICK_CAMERA_TO_CHANGE: '點擊相機圖示更換頭像',
  SUPPORTED_IMAGE_FORMATS: '支援 JPG、PNG、GIF、WebP（自動壓縮）',
  CHANGE_PASSWORD: '修改密碼',
  PASSWORD_SECURITY_TIP: '定期更換密碼以保護您的帳號安全',
  COLLAPSE: '收合',
  CURRENT_PASSWORD: '目前密碼',
  CURRENT_PASSWORD_PLACEHOLDER: '請輸入目前密碼',
  NEW_PASSWORD: '新密碼',
  NEW_PASSWORD_PLACEHOLDER: '至少8個字元',
  CONFIRM_NEW_PASSWORD: '確認新密碼',
  CONFIRM_PASSWORD_PLACEHOLDER: '再次輸入新密碼',
  PASSWORD_MATCH: '✓ 密碼確認一致',
  PASSWORD_MISMATCH: '✗ 密碼確認不一致',
  UPDATING: '更新中...',
  UPDATE_PASSWORD: '更新密碼',
  PASSWORD_REQUIREMENTS_TITLE: '📝 密碼要求：',
  PASSWORD_REQ_LENGTH: '至少8個字元',
  PASSWORD_REQ_FORMAT: '建議包含數字和字母',
  PASSWORD_REQ_CURRENT: '需要先輸入目前密碼進行驗證',
  
  // Avatar Upload Messages
  UNSUPPORTED_IMAGE_FORMAT: '只支援 JPG、PNG、GIF、WebP 格式的圖片',
  FILE_SIZE_TOO_LARGE: '檔案大小不能超過 10MB',
  UPLOAD_FAILED: '上傳失敗',
  AVATAR_UPLOAD_SUCCESS: '頭像上傳成功',
  AVATAR_UPLOAD_FAILED: '頭像上傳失敗：',
  
  // Password Change Messages
  PLEASE_LOGIN_FIRST: '請先登入',
  CURRENT_PASSWORD_REQUIRED: '請輸入目前密碼！',
  PASSWORDS_NOT_MATCH: '新密碼與確認密碼不符！',
  PASSWORD_TOO_SHORT: '密碼長度至少需要8個字元！',
  OFFLINE_PASSWORD_CHANGE: '目前離線，無法修改密碼。請連接網路後再試。',
  NETWORK_DISCONNECTED: '網路未連接',
  PASSWORD_UPDATE_FAILED: '密碼更新失敗',
  PASSWORD_UPDATE_SUCCESS: '密碼更新成功！',
  UPDATE_SUCCESS: '更新成功',
  PASSWORD_UPDATE_ERROR: '密碼更新失敗，請稍後再試',
  
  // Menu Settings
  MENU_SETTINGS: '選單設定',
  MENU_SETTINGS_DESC: '自訂側邊欄顯示的功能選單。隱藏不常用的功能，讓工作區更整潔。',
  CORE_FEATURES: '核心功能',
  CORE_FEATURES_DESC: '儀表板、工作區、設定等核心功能無法隱藏，確保系統正常運作。',
  SELECT_SIDEBAR_FEATURES: '選擇要在側邊欄顯示的功能',
  SAVING: '儲存中...',
  SAVE_SETTINGS: '儲存設定',
  RESET_TO_DEFAULT: '重設為預設',
  MENU_SETTINGS_SAVED: '選單設定已儲存',
  SAVE_FAILED: '儲存失敗，請稍後再試',
  RESET_CONFIRM_MESSAGE: '確定要重設為預設值嗎？所有選單都會顯示。',
  RESET_MENU_TITLE: '重設選單',
  HIDDEN_ITEMS_COUNT: '目前隱藏 {count} 個選單項目',
  
  // Permissions Page
  CROSS_WORKSPACE_PERMISSIONS: '跨分公司權限管理',
  PERMISSIONS_MANAGEMENT_DESC: '管理員工的跨分公司資料存取權限',
  FEATURE_DISABLED: '功能已停用',
  FEATURE_DISABLED_DESC: '此功能已根據系統架構決策停用',
  DISABLE_REASONS: '停用原因：',
  DISABLE_REASON_1: 'Venturo 是內部管理系統，員工都是信任的',
  DISABLE_REASON_2: '簡化架構，避免 RLS (Row Level Security) 帶來的複雜度',
  DISABLE_REASON_3: '提升效能，減少每次查詢的權限檢查開銷',
  DISABLE_REASON_4: '主管可能需要跨 workspace 查詢資料',
  DISABLE_REASON_5: '專注於業務邏輯開發，不處理資料庫層權限',
  EXISTING_PERMISSIONS: '現有權限控制方式：',
  AUTH_LOGIN: '登入驗證',
  FUNCTION_PERMISSIONS: '功能權限控制（查看人資設定）',
  DATA_ISOLATION: '資料隔離（前端 filter）',
  ROLE_LABELS: '角色標籤（admin, tour_leader 等）',
  REFERENCE_DOC: '參考文檔：',
}