export const LABELS = {
  // Header and Navigation
  SYSTEM_SETTINGS: '系統設定',
  HOME: '首頁',
  SETTINGS: '設定',
  USER: '使用者',
  LOGOUT: '登出',
  
  // Setup Mode
  WELCOME_TITLE: '歡迎！請完成帳號設定',
  FIRST_LOGIN_DESC: '這是您首次登入系統，請完成以下設定以確保帳號安全：',
  CHANGE_PASSWORD_TITLE: '1. 修改密碼',
  CHANGE_PASSWORD_DESC: '請將預設密碼改為您自己的密碼',
  UPLOAD_AVATAR_TITLE: '2. 上傳頭像',
  UPLOAD_AVATAR_DESC: '上傳您的照片，方便同事辨認',
  SKIP_LATER: '稍後再說',
  
  // Workspaces Page
  WORKSPACE_MANAGEMENT: '工作空間管理',
  WORKSPACE_MANAGEMENT_DESC: '管理多分公司設定，實現資料隔離（台北公司 vs 台中分公司）',
  ADD_WORKSPACE: '新增工作空間',
  DATA_ISOLATION_TITLE: '什麼是資料隔離？',
  DATA_ISOLATION_DESC: '工作空間可以確保不同分公司的資料獨立管理：',
  DATA_ISOLATION_POINT1: '• 台北員工預設看到台北的旅遊團、訂單、客戶',
  DATA_ISOLATION_POINT2: '• 台中員工預設看到台中的旅遊團、訂單、客戶',
  DATA_ISOLATION_POINT3: '• 系統管理員可以切換工作空間查看所有資料',
  DATA_ISOLATION_POINT4: '• 員工資料、航空公司、飯店等主檔仍然全公司共享',
  NO_DESCRIPTION: '無描述',
  STATUS_ACTIVE: '啟用',
  STATUS_INACTIVE: '停用',
  EMPLOYEE_COUNT: '員工數：{count} 人',
  EDIT: '編輯',
  EDIT_FEATURE_COMING: '編輯功能開發中',
  
  // Workspace Creation Dialog
  ADD_WORKSPACE_TITLE: '新增工作空間',
  WORKSPACE_NAME_LABEL: '名稱',
  WORKSPACE_NAME_REQUIRED: '*',
  WORKSPACE_NAME_PLACEHOLDER: '例如：台北總公司、台中分公司',
  WORKSPACE_DESCRIPTION_LABEL: '說明',
  WORKSPACE_DESCRIPTION_PLACEHOLDER: '簡短說明此工作空間',
  CANCEL: '取消',
  CREATE: '建立',
  
  // Messages and Notifications
  WORKSPACE_NAME_REQUIRED_MSG: '請填寫工作空間名稱',
  ANNOUNCEMENT: '公告',
  ANNOUNCEMENT_CHANNEL_DESC: '此頻道用於發布全工作空間的重要公告。',
  BOT_CREATION_FAILED: '建立機器人失敗（不影響 workspace 建立）',
  WORKSPACE_CREATED_SUCCESS: '工作空間、公告頻道和機器人已建立',
  CREATION_FAILED: '建立失敗',
  
  // Empty State
  NO_WORKSPACE_TITLE: '尚未建立工作空間',
  NO_WORKSPACE_DESC: '開始建立第一個工作空間以啟用多分公司管理',
  
  // Account Settings
  ACCOUNT_SECURITY: '帳號安全',
  AVATAR: '頭像',
  PERSONAL_AVATAR: '個人頭像',
  CLICK_CAMERA_TO_CHANGE: '點擊相機圖示更換頭像',
  SUPPORTED_IMAGE_FORMATS: '支援 JPG、PNG、GIF、WebP（自動壓縮）',
  CHANGE_PASSWORD: '修改密碼',
  PASSWORD_SECURITY_TIP: '定期更換密碼以保護您的帳號安全',
  COLLAPSE: '收合',
  CURRENT_PASSWORD: '目前密碼',
  CURRENT_PASSWORD_PLACEHOLDER: '請輸入目前密碼',
  NEW_PASSWORD: '新密碼',
  NEW_PASSWORD_PLACEHOLDER: '至少8個字元',
  CONFIRM_NEW_PASSWORD: '確認新密碼',
  CONFIRM_PASSWORD_PLACEHOLDER: '再次輸入新密碼',
  PASSWORD_MATCH: '✓ 密碼確認一致',
  PASSWORD_MISMATCH: '✗ 密碼確認不一致',
  UPDATING: '更新中...',
  UPDATE_PASSWORD: '更新密碼',
  PASSWORD_REQUIREMENTS_TITLE: '📝 密碼要求：',
  PASSWORD_REQ_LENGTH: '至少8個字元',
  PASSWORD_REQ_FORMAT: '建議包含數字和字母',
  PASSWORD_REQ_CURRENT: '需要先輸入目前密碼進行驗證',
  
  // Avatar Upload Messages
  UNSUPPORTED_IMAGE_FORMAT: '只支援 JPG、PNG、GIF、WebP 格式的圖片',
  FILE_SIZE_TOO_LARGE: '檔案大小不能超過 10MB',
  UPLOAD_FAILED: '上傳失敗',
  AVATAR_UPLOAD_SUCCESS: '頭像上傳成功',
  AVATAR_UPLOAD_FAILED: '頭像上傳失敗：',
  
  // Password Change Messages
  PLEASE_LOGIN_FIRST: '請先登入',
  CURRENT_PASSWORD_REQUIRED: '請輸入目前密碼！',
  PASSWORDS_NOT_MATCH: '新密碼與確認密碼不符！',
  PASSWORD_TOO_SHORT: '密碼長度至少需要8個字元！',
  OFFLINE_PASSWORD_CHANGE: '目前離線，無法修改密碼。請連接網路後再試。',
  NETWORK_DISCONNECTED: '網路未連接',
  PASSWORD_UPDATE_FAILED: '密碼更新失敗',
  PASSWORD_UPDATE_SUCCESS: '密碼更新成功！',
  UPDATE_SUCCESS: '更新成功',
  PASSWORD_UPDATE_ERROR: '密碼更新失敗，請稍後再試',
  
  // Menu Settings
  MENU_SETTINGS: '選單設定',
  MENU_SETTINGS_DESC: '自訂側邊欄顯示的功能選單。隱藏不常用的功能，讓工作區更整潔。',
  CORE_FEATURES: '核心功能',
  CORE_FEATURES_DESC: '儀表板、工作區、設定等核心功能無法隱藏，確保系統正常運作。',
  SELECT_SIDEBAR_FEATURES: '選擇要在側邊欄顯示的功能',
  SAVING: '儲存中...',
  SAVE_SETTINGS: '儲存設定',
  RESET_TO_DEFAULT: '重設為預設',
  MENU_SETTINGS_SAVED: '選單設定已儲存',
  SAVE_FAILED: '儲存失敗，請稍後再試',
  RESET_CONFIRM_MESSAGE: '確定要重設為預設值嗎？所有選單都會顯示。',
  RESET_MENU_TITLE: '重設選單',
  HIDDEN_ITEMS_COUNT: '目前隱藏 {count} 個選單項目',
  
  // Permissions Page
  CROSS_WORKSPACE_PERMISSIONS: '跨分公司權限管理',
  PERMISSIONS_MANAGEMENT_DESC: '管理員工的跨分公司資料存取權限',
  FEATURE_DISABLED: '功能已停用',
  FEATURE_DISABLED_DESC: '此功能已根據系統架構決策停用',
  DISABLE_REASONS: '停用原因：',
  DISABLE_REASON_1: 'Venturo 是內部管理系統，員工都是信任的',
  DISABLE_REASON_2: '簡化架構，避免 RLS (Row Level Security) 帶來的複雜度',
  DISABLE_REASON_3: '提升效能，減少每次查詢的權限檢查開銷',
  DISABLE_REASON_4: '主管可能需要跨 workspace 查詢資料',
  DISABLE_REASON_5: '專注於業務邏輯開發，不處理資料庫層權限',
  EXISTING_PERMISSIONS: '現有權限控制方式：',
  AUTH_LOGIN: '登入驗證',
  FUNCTION_PERMISSIONS: '功能權限控制（查看人資設定）',
  DATA_ISOLATION: '資料隔離（前端 filter）',
  ROLE_LABELS: '角色標籤（admin, tour_leader 等）',
  REFERENCE_DOC: '參考文檔：',
  RLS_SPEC_DOC: 'CLAUDE.md - RLS 規範',
  
  // System Settings
  SYSTEM_MAINTENANCE: '系統維護',
  CLEAR_LOCAL_CACHE: '清除本地快取',
  CLEAR_CACHE_DESC: '清除所有本地儲存的資料，包括 IndexedDB、localStorage 和 sessionStorage。 清除後會從 Supabase 重新載入最新資料。',
  DB_STATUS: '資料庫狀態',
  DB_CREATED: '已建立',
  DB_NOT_CREATED: '未建立',
  LOCAL_TABLES: '本地資料表',
  LOCAL_TABLES_UNIT: '個',
  CLEARING: '清除中...',
  CLEAR_CACHE_BTN: '清除快取',
  CLEAR_CACHE_WARNING: '清除快取會刪除所有本地儲存的資料，但不會影響 Supabase 雲端資料庫。如果遇到資料同步問題或顯示異常時，可以使用此功能重置本地快取。',
  CLEAR_CACHE_CONFIRM_MSG: '確定要清除所有本地快取嗎？\n\n這會刪除：\n• IndexedDB 本地資料庫\n• localStorage 儲存的狀態\n• sessionStorage 暫存資料\n\n清除後系統會重新整理，從 Supabase 載入最新資料。',
  CLEAR_CACHE_CONFIRM_TITLE: '清除快取確認',
  CLEAR_CACHE_SUCCESS: '快取已成功清除！\n頁面即將重新載入...',
  CLEAR_CACHE_SUCCESS_TITLE: '清除成功',
  CLEAR_CACHE_BLOCKED: '無法清除快取：請關閉所有 Venturo 分頁後再試',
  CLEAR_CACHE_FAILED: '清除快取失敗，請稍後再試',
  CLEAR_CACHE_TIMING_TITLE: '📝 建議使用時機：',
  CLEAR_CACHE_TIMING_1: '資料顯示異常或不正確',
  CLEAR_CACHE_TIMING_2: '系統更新後需要重新初始化',
  CLEAR_CACHE_TIMING_3: '遇到資料同步問題',
  CLEAR_CACHE_TIMING_4: '本地快取損壞或過期',

  // Appearance Settings
  THEME_SETTINGS: '主題設定',
  MORANDI_THEME_NAME: '莫蘭迪優雅',
  MORANDI_THEME_DESC: '柔和的色彩，溫暖的米色背景，適合長時間使用',
  MODERN_DARK_NAME: '現代深色',
  MODERN_DARK_DESC: '深色背景，高對比度，現代感十足的設計',
  NORDIC_THEME_NAME: '北歐簡約',
  NORDIC_THEME_DESC: '清新明亮，極簡設計，專注於內容呈現',
  THEME_TIP_TITLE: '提示：',
  THEME_TIP_DESC: '主題設定會立即生效並自動儲存。不同主題適合不同的使用場景和個人喜好。',
}
export const API_SETTINGS_LABELS = {
  LOADING: '載入中...',
  API_KEY_WARNING: '請勿將 API Key 分享給非授權人員',
  SETUP_GUIDE: '設定方式',
  TITLE: 'API 設定',

  SETTINGS_4369: '未設定',
  NOT_SET: '未設定',
  COPY: '複製',
  LABEL_4474: '檔案：',
  HIDE: '隱藏',
  SHOW: '顯示',
  ADMIN_CONSOLE: '管理後台',
  DOCS: '文件',
  CATEGORY_DATABASE: 'Supabase 資料庫',
  CATEGORY_OCR: 'OCR 辨識服務',
  CATEGORY_AI: 'AI 服務',
  CATEGORY_FLIGHT: '航班查詢服務',
  CATEGORY_PAYMENT: '金流服務',
  CATEGORY_OTHER: '其他設定',
  ENV_FILE_PREFIX: '在專案根目錄建立或編輯',
}

export const DEVTOOLS_LABELS = {
  TITLE: '開發者工具',
  ONE_CLICK_ENV: '一鍵設定 .env.local',
  STEP_COPY: '點擊「複製指令」按鈕',
  STEP_OPEN_TERMINAL: '開啟 Claude Code 終端機',
  STEP_PASTE: '貼上複製的內容',
  STEP_RESTART: '重啟開發伺服器：',

  COPYING_1479: '複製後貼給 Claude Code，自動建立完整環境設定',
  COPYING_9243: '已複製！',
  COPYING_539: '複製指令',
  SETTINGS_6471: '用於設定 Vercel 專案的環境變數',
  COPYING_4512: '複製清單',
  LABEL_2441: '使用方式：',
  COLLAPSE: '收起',
  EXPAND: '展開',
  VERCEL_ENV_LIST: 'Vercel 環境變數清單',
  COPIED: '已複製！',
  ENV_PREVIEW: '.env.local 完整內容預覽：',
  STEP_CLAUDE_AUTO: 'Claude Code 會自動建立 .env.local 檔案',
}

export const MODULE_MANAGEMENT_LABELS = {
  TITLE: '系統模組管理',
  AUTH_MANAGEMENT: '模組授權管理',

  MANAGE_4601: '管理工作空間的系統模組（會計、庫存、BI 分析等）',
  MANAGE_8355: '管理模組',
  LABEL_1050: '啟用/停用系統模組（會計模組、庫存模組等）',
  SETTINGS_5976: '設定模組授權到期日',
  LABEL_3126: '查看各模組的功能特性',
}

export const NEWEBPAY_LABELS = {
  TITLE: '藍新金流設定',
  LOADING: '載入中...',
  SUBTITLE: '旅行業代收轉付電子收據',
  MERCHANT_ID: '商店代號 (MerchantID)',
  MERCHANT_ID_HINT: '在藍新後台「商店管理」可查看',
  SETUP_GUIDE: '設定說明',
  GUIDE_1: '請先在藍新金流申請「旅行業代收轉付電子收據」服務',
  GUIDE_3: '測試環境可使用測試商店代號進行開發測試',
  GUIDE_4: '正式上線前請切換到正式環境並使用正式商店資訊',

  LABEL_8125: '輸入藍新商店代號',
  LABEL_6384: '輸入 32 字元的 HashKey',
  LABEL_1330: '輸入 16 字元的 HashIV',
  LABEL_2112: '正式環境',
  HASHKEY_HINT: '32 字元，在藍新後台「API 串接資訊」可查看',
  HASHIV_HINT: '16 字元，在藍新後台「API 串接資訊」可查看',
  ENV_PRODUCTION: '目前使用正式環境 (api.travelinvoice.com.tw)',
  ENV_TEST: '目前使用測試環境 (capi.travelinvoice.com.tw)',
  SAVING: '儲存中...',
  SAVE: '儲存設定',
  GUIDE_2: 'HashKey 和 HashIV 是加密用金鑰，請妥善保管',
  LOAD_FAILED: '載入設定失敗',
  SAVE_SUCCESS: '設定已儲存',
  SAVE_FAILED: '儲存設定失敗',
}

export const OTHER_SETTINGS_LABELS = {
  TITLE: '其他設定',
  LANGUAGE_SETTING: '語言設定',
  LANGUAGE_VALUE: '繁體中文（預設）',
  NOTIFICATION_SETTING: '通知設定',
  NOTIFICATION_VALUE: '系統通知：開啟',
  BACKUP_SETTING: '資料備份',
  BACKUP_VALUE: '自動備份：每日凌晨 2:00',
}

export const PERMISSION_LABELS = {
  TITLE: '權限管理',
  BRANCH_MANAGEMENT: '分公司管理',
  MANAGE_BRANCHES: '管理分公司',
  CROSS_BRANCH_PERMISSION: '跨分公司權限',
  PERM_1: '授權特定員工跨分公司查看資料',
  PERM_2: '設定不同權限等級（查看、編輯、刪除、財務）',
  PERM_3: '設定權限過期時間（可選）',
  PERM_4: '隨時撤銷權限',
  PERMISSION_SETTINGS: '權限設定',

  MANAGE_2715: '管理所有分公司（台北、台中等），建立新分公司、查看員工分佈',
  MANAGE_9542: '授權管理員查看或管理其他分公司的資料（例如：台北管理員可查看台中的旅遊團）',
}

export const PREFERRED_FEATURES_LABELS = {
  SAVING: '儲存中...',
  SAVED: '已儲存',
  PENDING_SAVE: '變更待儲存...',
  DESCRIPTION_TITLE: '說明',
  DESC_1: '選擇的功能會顯示在側邊欄，未選擇的會被隱藏',
  DESC_2: '此設定不影響你的實際權限，只是個人化介面顯示',
  DESC_3: '你只能選擇有權限的功能',
  DESC_4: '變更會在停止操作後自動儲存',

  SETTINGS_6020: '常用功能設定',
  SELECT_5572: '選擇你常用的功能，側邊欄將只顯示這些項目，讓介面更簡潔',
  LABEL_1762: '恢復角色預設',

  // Feature labels
  FEATURE_CALENDAR: '行事曆',
  FEATURE_WORKSPACE: '工作空間',
  FEATURE_TODOS: '待辦事項',
  FEATURE_TOURS: '旅遊團',
  FEATURE_ORDERS: '訂單',
  FEATURE_QUOTES: '報價單',
  FEATURE_CUSTOMERS: '顧客管理',
  FEATURE_BUSINESS: '行程管理',
  FEATURE_CONFIRMATIONS: '確認單管理',
  FEATURE_CONTRACTS: '合約管理',
  FEATURE_VISAS: '簽證管理',
  FEATURE_FINANCE: '財務系統',
  FEATURE_PAYMENTS: '收款管理',
  FEATURE_REQUESTS: '請款管理',
  FEATURE_DISBURSEMENT: '出納管理',
  FEATURE_ACCOUNTING: '記帳',
  FEATURE_VOUCHERS: '會計傳票',
  FEATURE_REPORTS: '報表管理',
  FEATURE_DATABASE: '資料管理',
  FEATURE_HR: '人資管理',
  FEATURE_SETTINGS: '系統設定',

  // Feature descriptions
  DESC_CALENDAR: '個人及團隊行程管理',
  DESC_WORKSPACE: '工作空間資訊與設定',
  DESC_TODOS: '個人待辦清單',
  DESC_TOURS: '旅遊團管理與行程規劃',
  DESC_ORDERS: '客戶訂單管理',
  DESC_QUOTES: '報價單製作與管理',
  DESC_CUSTOMERS: '客戶資料維護',
  DESC_BUSINESS: '旅遊行程規劃',
  DESC_CONFIRMATIONS: '確認單製作與管理',
  DESC_CONTRACTS: '合約簽署與管理',
  DESC_VISAS: '簽證申請追蹤',
  DESC_FINANCE: '財務管理總覽',
  DESC_PAYMENTS: '客戶付款追蹤',
  DESC_REQUESTS: '內部請款作業',
  DESC_DISBURSEMENT: '款項支付管理',
  DESC_ACCOUNTING: '會計記帳作業',
  DESC_VOUCHERS: '會計憑證管理',
  DESC_REPORTS: '財務報表產生',
  DESC_DATABASE: '系統資料維護',
  DESC_HR: '員工管理與權限設定',
  DESC_SETTINGS: '個人與系統設定',

  // Categories
  CAT_CORE: '核心功能',
  CAT_BUSINESS: '業務功能',
  CAT_FINANCE: '財務功能',
  CAT_DATA: '資料管理',
  CAT_MANAGEMENT: '管理功能',

  // Inline JSX
  SELECTED_COUNT_PREFIX: '已選擇 ',
  SELECTED_COUNT_SUFFIX: ' 個功能',
  NO_PERMISSION: '(無權限)',
}

export const WORKSPACE_SWITCHER_LABELS = {
  TITLE: '工作空間切換',
  VIEW_ALL: '查看全部辦公室',

  LABEL_795: '切換查看特定辦公室的資料，或查看所有辦公室的資料',
  SWITCH_HINT: '💡 切換後，所有列表（旅遊團、訂單、客戶等）都會只顯示該辦公室的資料',
}

export const MODULES_PAGE_LABELS = {
  STATUS: '狀態',
  EXPIRY_DATE: '到期日',
  FEATURES: '功能特性',
  MODULE_DESC_TITLE: '模組說明',
  DESC_1: '模組需要啟用後才能使用相關功能',
  DESC_2: '可設定到期日，過期後會自動停用',
  DESC_3: '停用模組不會刪除已建立的資料，重新啟用後可繼續使用',
  DESC_4: '每個工作空間可獨立管理模組授權',
  EXPIRY_LABEL: '授權到期日（選填）',
  EXPIRY_HINT: '留空表示永久授權',
  INCLUDED_FEATURES: '包含功能',

  MANAGE_8474: '系統模組管理',
  LABEL_795: '當前工作空間',
  LABEL_2710: '已啟用',
  LABEL_8966: '已過期',
  LABEL_5400: '未啟用',
  LABEL_5213: '停用模組',
  SELECT_5234: '選擇日期',
  CANCEL: '取消',

  // Module info
  ACCOUNTING_NAME: '會計模組',
  ACCOUNTING_DESC: '完整的會計傳票系統，支援自動拋轉與財務報表',
  ACCOUNTING_FEATURES: ['自動產生會計傳票', '收款/付款自動拋轉', '結團自動產生收入與成本傳票', '手工傳票輸入', '傳票過帳與作廢', '借貸平衡檢查'] as const,
  INVENTORY_NAME: '庫存模組',
  INVENTORY_DESC: '庫存管理系統（開發中）',
  INVENTORY_FEATURES: ['庫存追蹤', '進銷存管理', '盤點功能', '庫存警報'] as const,
  BI_NAME: 'BI 分析模組',
  BI_DESC: 'Business Intelligence 商業智能分析（開發中）',
  BI_FEATURES: ['銷售分析', '成本分析', '利潤分析', '自訂報表'] as const,

  // Toast messages
  MODULE_ENABLED: (name: string) => `${name} 已啟用`,
  ENABLE_FAILED: '啟用失敗，請稍後再試',
  DISABLE_CONFIRM: (name: string) => `確定要停用 ${name} 嗎？\n\n停用後相關功能將無法使用。`,
  DISABLE_MODULE: '停用模組',
  MODULE_DISABLED: (name: string) => `${name} 已停用`,
  DISABLE_FAILED: '停用失敗，請稍後再試',
  UNKNOWN_WORKSPACE: '未知工作空間',

  // Breadcrumb
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_SETTINGS: '設定',
  BREADCRUMB_MODULES: '模組管理',

  // Buttons
  RE_ENABLE: '重新啟用',
  ENABLE_MODULE: '啟用模組',
  PROCESSING: '處理中...',
  CONFIRM_ENABLE: '確認啟用',
  WORKSPACE_ID_LABEL: (id: string) => `工作空間 ID: ${id}`,
  ENABLE_DIALOG_TITLE: (name: string) => `啟用 ${name}`,
}
