export const TOUR_CLOSING_LABELS = {
  LABEL_5942: '結團報表',
  LABEL_2902: '全部月份',
  EXPORT_7131: '匯出 Excel',
  COL_TOUR_CODE: '團號',
  COL_TOUR_NAME: '團名',
  COL_DEPARTURE: '出發日',
  COL_CLOSING: '結團日',
  COL_REVENUE: '收入',
  COL_COST: '成本',
  COL_NET_PROFIT: '淨利',
  EXPORT_TOUR: '匯出此團',
  // Previously hardcoded strings
  WORKSPACE_NOT_FOUND: '找不到工作空間',
  LOAD_FAILED: '載入報表失敗',
  NO_DATA_TO_EXPORT: '沒有資料可匯出',
  REPORT_EXPORTED: '報表已匯出',
  SEARCH_PLACEHOLDER: '搜尋團號或團名...',
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_REPORTS: '報表',
  BREADCRUMB_TOUR_CLOSING: '結團報表',
  EXCEL_FILENAME_PREFIX: '結團報表',
  // Bonus supplier_name matching (these are DB values, kept as constants)
  BONUS_SALES: '業務業績',
  BONUS_OP: 'OP 獎金',
  BONUS_TEAM: '團體獎金',
  UNKNOWN_EMPLOYEE: '未知',
  // Excel column headers
  EXCEL_TOUR_CODE: '團號',
  EXCEL_TOUR_NAME: '團名',
  EXCEL_DEPARTURE: '出發日',
  EXCEL_RETURN: '返回日',
  EXCEL_CLOSING: '結團日',
  EXCEL_SALES: '業務',
  EXCEL_OP: 'OP',
  EXCEL_ORDER_AMOUNT: '訂單金額',
  EXCEL_COST: '成本',
  EXCEL_ADMIN_FEE: '行政費(人數×10)',
  EXCEL_TAX: '扣稅12%',
  EXCEL_TEAM_BONUS: '團體獎金',
  EXCEL_SALES_BONUS: '業務獎金',
  EXCEL_OP_BONUS: 'OP獎金',
  EXCEL_GROSS_PROFIT: '毛利',
  EXCEL_NET_PROFIT: '淨利',
}
