export const ERP_ACCOUNTING_LABELS = {
  PAGE_TITLE: '會計系統',
  BREADCRUMB_HOME: '首頁',
  BREADCRUMB_FINANCE: '財務管理',
  BREADCRUMB_ACCOUNTING: '會計系統',
  SEARCH_PLACEHOLDER: '搜尋...',
  SEARCH_TITLE: '搜尋',
  TAB_VOUCHERS: '傳票',
  TAB_REPORTS: '報表',
  TAB_ACCOUNT_SETTINGS: '科目設定',
  TAB_PERIOD_CLOSING: '期末結帳',
}
