-- ============================================
-- 頂級旅遊資料庫種子資料
-- 米其林餐廳 + 頂級在地體驗
-- ============================================

BEGIN;

-- ============================================
-- 🌟 米其林餐廳資料 - 日本
-- ============================================

-- 1. 數寄屋橋次郎（東京）- 全球最難訂位的壽司
INSERT INTO public.michelin_restaurants (
  name,
  name_en,
  name_local,
  michelin_stars,
  michelin_guide_year,
  country_id,
  city_id,
  address,
  cuisine_type,
  dining_style,
  price_range,
  avg_price_lunch,
  avg_price_dinner,
  currency,
  phone,
  reservation_required,
  description,
  chef_name,
  chef_profile,
  signature_dishes,
  specialties,
  facilities,
  dress_code,
  dining_restrictions,
  commission_rate,
  booking_notes,
  recommended_for,
  best_season,
  is_active
) VALUES (
  '数寄屋橋次郎',
  'Sukiyabashi Jiro',
  'すきやばしじろう',
  3,
  2024,
  (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '東京' AND country_id = (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1) LIMIT 1),
  '東京都中央區銀座4-2-15 塚本大樓地下1樓',
  ARRAY['江戶前壽司', '日本料理'],
  'Fine Dining',
  '$$$$',
  NULL, -- 不提供午餐
  40000,
  'JPY',
  '+81-3-3535-3600',
  TRUE,
  '由壽司之神小野二郎親手製作的江戶前壽司，被譽為全球最難訂位的餐廳。每日僅提供晚餐，座位僅10席，需透過五星級飯店禮賓部預約。',
  '小野二郎',
  '95歲高齡的壽司之神，70年壽司職人生涯，2011年紀錄片《壽司之神》主角。',
  ARRAY['赤身', '中トロ', '大トロ', '車海老', '煮蛤'],
  ARRAY['全球最高齡米其林三星主廚', '歐巴馬曾造訪', '僅10個吧台座位', '無菜單Omakase'],
  '{"parking": false, "wheelchair_accessible": false, "private_room": false, "counter_seating_only": true}',
  'Smart Casual（建議正裝）',
  '{"no_photography": true, "no_children_under_12": true, "omakase_only": true, "duration_30_minutes": true}',
  5.00,
  '需透過五星級飯店禮賓部預約，至少提前3個月。強烈建議安排翻譯陪同。用餐時間嚴格控制在30分鐘內。',
  ARRAY['once_in_lifetime', 'culinary_pilgrimage', 'vip_客戶', 'honeymoon'],
  ARRAY['全年'],
  TRUE
);

-- 2. 龍吟（東京）- 現代創意日本料理
INSERT INTO public.michelin_restaurants (
  name, name_en, name_local,
  michelin_stars, michelin_guide_year,
  country_id, city_id,
  address,
  cuisine_type, dining_style, price_range,
  avg_price_lunch, avg_price_dinner, currency,
  phone, reservation_required,
  description,
  chef_name, chef_profile,
  signature_dishes,
  commission_rate,
  group_menu_available,
  recommended_for,
  is_active
) VALUES (
  '龍吟',
  'Nihonryori RyuGin',
  'にほんりょうりりゅうぎん',
  3, 2024,
  (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '東京' AND country_id = (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1) LIMIT 1),
  '東京都港區六本木7-17-24',
  ARRAY['現代日本料理', '創意料理'],
  'Fine Dining',
  '$$$$',
  25000, 35000, 'JPY',
  '+81-3-3423-8006',
  TRUE,
  '世界50最佳餐廳常客，主廚山本征治將傳統日本料理昇華至藝術境界。',
  '山本征治',
  '曾在「世界50最佳餐廳」排名第7，擅長將季節食材轉化為感官體驗。',
  ARRAY['蠑螺最中', '鮑魚肝醬', '季節懷石'],
  8.00,
  TRUE,
  ARRAY['luxury_traveler', 'food_enthusiast', 'business_entertainment'],
  TRUE
);

-- ============================================
-- 🌟 米其林餐廳資料 - 法國
-- ============================================

-- 3. L'Arpège（巴黎）- 蔬菜料理的極致
INSERT INTO public.michelin_restaurants (
  name, name_en,
  michelin_stars, michelin_guide_year, green_star,
  country_id, city_id,
  address, address_en,
  cuisine_type, dining_style, price_range,
  avg_price_lunch, avg_price_dinner, currency,
  phone, website, reservation_url,
  description, description_en,
  chef_name, chef_profile,
  signature_dishes,
  specialties,
  commission_rate,
  recommended_for,
  is_active
) VALUES (
  'L''Arpège',
  'L''Arpège',
  3, 2024, TRUE,
  (SELECT id FROM public.countries WHERE code = 'FR' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '巴黎' AND country_id = (SELECT id FROM public.countries WHERE code = 'FR' LIMIT 1) LIMIT 1),
  '84 Rue de Varenne, 75007 Paris',
  '84 Rue de Varenne, 7th Arrondissement, Paris',
  ARRAY['法式料理', '蔬食料理'],
  'Fine Dining',
  '$$$$',
  180, 380, 'EUR',
  '+33-1-47-05-09-06',
  'https://www.alain-passard.com',
  'https://www.alain-passard.com/reservations',
  '主廚Alain Passard擁有3座自營有機農場，每日清晨採摘送抵巴黎，將蔬菜料理推向極致。曾獲米其林綠星認證。',
  'Chef Alain Passard owns 3 organic farms, with daily morning harvests delivered to Paris, elevating vegetable cuisine to art. Awarded Michelin Green Star.',
  'Alain Passard',
  '1986年獲得第一顆米其林星星時僅30歲，1996年摘下三星後於2001年做出驚人決定：菜單去除紅肉，專注於蔬菜料理。',
  ARRAY['Beetroot in a Salt Crust', 'Tomato Tart', 'Egg with Maple Syrup'],
  ARRAY['三座有機農場', '綠星認證', '蔬菜料理先驅', 'Art Deco裝潢'],
  10.00,
  ARRAY['vegetarian_friendly', 'sustainable_dining', 'romantic_dinner', 'special_occasion'],
  TRUE
);

-- ============================================
-- 🎭 頂級在地體驗 - 日本
-- ============================================

-- 1. 京都祇園私人藝伎茶宴
INSERT INTO public.premium_experiences (
  name, name_en, name_local,
  tagline,
  country_id, city_id,
  specific_location,
  category, sub_category,
  exclusivity_level,
  description,
  highlights,
  what_makes_it_special,
  expert_name, expert_title, expert_credentials,
  duration_hours,
  group_size_min, group_size_max,
  language_support,
  difficulty_level,
  available_seasons,
  best_time_of_day,
  advance_booking_days,
  price_per_person_min, price_per_person_max, currency,
  price_includes,
  price_excludes,
  commission_rate,
  net_price_per_person,
  booking_notes,
  dress_code,
  what_to_bring,
  restrictions,
  meeting_point,
  inclusions,
  recommended_for,
  suitable_for_children,
  sustainability_practices,
  supports_local_community,
  is_active, is_featured
) VALUES (
  '祇園花街私人藝伎茶宴',
  'Private Geisha Tea Ceremony in Gion',
  'ぎおんかがいのおざしきあそび',
  '走入真正的花街世界，與舞伎、藝伎共度私密時光',
  (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '京都' AND country_id = (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1) LIMIT 1),
  '祇園甲部歌舞練場附近的傳統お茶屋（茶屋）',
  'cultural_immersion',
  ARRAY['traditional_arts', 'exclusive_access', 'cultural_heritage'],
  'highly_exclusive',
  '這不是觀光表演，而是進入真正藝伎世界的獨特機會。在祇園最古老的茶屋之一，由資深的置屋媽媽桑親自安排，與正牌舞伎或藝伎共度私密茶宴。您將體驗真正的「お座敷遊び」（宴席遊戲），欣賞傳統舞蹈與三味線演奏，並學習花街獨有的禮儀與文化。',
  ARRAY[
    '由擁有60年經歷的置屋媽媽桑親自接待',
    '與資深藝伎或新進舞伎面對面交流（含翻譯）',
    '品嘗京都傳統懷石料理',
    '觀賞傳統舞蹈與三味線現場演奏',
    '學習日本傳統遊戲「投扇興」',
    '獲得藝伎親筆簽名的精美團扇作為紀念'
  ],
  '這是極少數外國旅客能進入真正茶屋的機會。祇園的茶屋採取「一見さんお断り」（拒絕生客）制度，只接待熟客介紹的賓客。我們透過三代往來的關係，為您打開這扇神秘的門。',
  '岡本幸代',
  '資深置屋媽媽桑',
  ARRAY['經營茶屋60年', '培育過23位藝伎和舞伎', '祇園甲部歌舞會榮譽顧問'],
  3.0,
  2, 6,
  ARRAY['日語', '英語', '中文'],
  'easy',
  ARRAY['春', '夏', '秋', '冬'],
  'evening',
  45,
  120000, 150000, 'JPY',
  ARRAY['私人茶屋包場', '懷石料理', '藝伎或舞伎表演', '專業攝影記錄（含修圖）', '翻譯服務', '紀念團扇'],
  ARRAY['往返交通', '額外酒水'],
  15.00,
  102000,
  '此體驗需提前45-60天預約。藝伎的檔期極為搶手，櫻花季和楓葉季需提前3個月。強烈建議安排在京都停留的最後一晚，作為行程的完美句點。',
  'Smart Casual（避免過度休閒）',
  ARRAY['相機（可拍照但需遵守禮儀）', '名片（如欲交換）'],
  ARRAY['禁止觸摸藝伎的衣物和髮飾', '禁止過度飲酒', '需脫鞋入內', '建議12歲以上參加'],
  '京都市東山區祇園町南側（具體地址預約後告知）',
  '{"meals": ["kaiseki_dinner"], "performances": ["traditional_dance", "shamisen"], "souvenirs": ["signed_fan"], "photos": ["professional_photography"]}',
  ARRAY['once_in_lifetime', 'culture_enthusiast', 'luxury_traveler', 'honeymoon', 'special_occasion'],
  FALSE,
  ARRAY['支持傳統工藝傳承', '全程使用京都在地食材'],
  TRUE,
  TRUE, TRUE
);

-- 2. 備前刀匠三代目工房見學與刀劍製作體驗
INSERT INTO public.premium_experiences (
  name, name_en,
  tagline,
  country_id, city_id,
  specific_location,
  category, sub_category,
  exclusivity_level,
  description,
  highlights,
  what_makes_it_special,
  expert_name, expert_title, expert_credentials,
  duration_hours,
  group_size_min, group_size_max,
  language_support,
  difficulty_level,
  physical_requirement,
  advance_booking_days,
  price_per_person_min, price_per_person_max, currency,
  commission_rate,
  recommended_for,
  certifications,
  is_active, is_featured
) VALUES (
  '備前刀匠三代傳承工房見學',
  'Bizen Sword Smithing Experience with 3rd Generation Master',
  '跟隨日本刀國寶級匠人，見證千年技藝的傳承',
  (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '岡山' AND country_id = (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1) LIMIT 1),
  '岡山縣瀨戶內市長船町（日本刀的故鄉）',
  'artisan_workshop',
  ARRAY['traditional_crafts', 'cultural_heritage', 'hands_on'],
  'ultra_exclusive',
  '備前長船是日本刀的聖地，700年來孕育了無數名刀。跟隨刀匠三代目深入工房，親眼見證「玉鋼」鍛造的神聖過程，在1200度的高溫中感受鐵與火的對話。您將親手參與部分鍛造工序，製作專屬的小刀具（ペーパーナイフ）帶回家。',
  ARRAY[
    '由經濟產業大臣指定傳統工藝士親自指導',
    '參觀通常不對外開放的私人工房',
    '見證玉鋼鍛造的完整過程（千錘百鍊）',
    '親手體驗刀劍鍛打（在匠人協助下）',
    '製作專屬刻字小刀帶回',
    '獲得刀匠親筆簽名的合格證書'
  ],
  '全日本僅有約300位現役刀匠，其中僅10%願意接受外國訪客。我們的合作匠人來自三代傳承的刀匠世家，其祖父曾為昭和天皇打造御刀。',
  '長船清光',
  '人間國寶刀匠三代目',
  ARRAY['經濟產業大臣指定傳統工藝士', '全日本刀劍保存協會特別認定', '三代傳承（1920年創業）'],
  6.0,
  1, 4,
  ARRAY['日語', '英語'],
  'moderate',
  '需能站立6小時，並在匠人協助下使用鎚子',
  90,
  180000, 220000, 'JPY',
  20.00,
  ARRAY['culture_enthusiast', 'history_lover', 'craft_lover', 'once_in_lifetime'],
  ARRAY['經濟產業大臣指定傳統工藝士', '岡山縣無形文化財保持者'],
  TRUE, TRUE
);

-- 3. 北海道私人雪地奢華帳篷晚餐（冬季限定）
INSERT INTO public.premium_experiences (
  name, name_en,
  tagline,
  country_id, city_id,
  specific_location,
  category, sub_category,
  exclusivity_level,
  description,
  highlights,
  what_makes_it_special,
  duration_hours,
  group_size_min, group_size_max,
  language_support,
  difficulty_level,
  available_seasons,
  advance_booking_days,
  price_per_person_min, price_per_person_max, currency,
  price_includes,
  commission_rate,
  recommended_for,
  inclusions,
  transportation_included,
  pickup_service,
  is_active, is_featured
) VALUES (
  '北海道秘境雪地奢華晚宴',
  'Private Luxury Snow Dome Dining in Hokkaido',
  '在璀璨星空下，於純白雪原中享受頂級法日fusion料理',
  (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1),
  (SELECT id FROM public.cities WHERE name = '札幌' AND country_id = (SELECT id FROM public.countries WHERE code = 'JP' LIMIT 1) LIMIT 1),
  '十勝岳麓秘境雪原（距離富良野約30分鐘）',
  'culinary_mastery',
  ARRAY['exclusive_dining', 'nature_experience', 'luxury'],
  'exclusive',
  '想像在零下20度的雪原中，坐在溫暖如春的透明圓頂帳篷裡，頭頂是滿天星斗，腳下是皚皚白雪，面前是米其林主廚現場烹調的頂級料理。這是只有冬季（12-3月）才能體驗的奢華饗宴。',
  ARRAY[
    '私人透明圓頂帳篷（配備暖爐與豪華座椅）',
    '米其林一星主廚現場烹調',
    '10道式法日fusion晚宴',
    '香檳與北海道葡萄酒無限暢飲',
    '專業星空導覽（天氣允許）',
    '雪地篝火與熱紅酒',
    '豪華車輛接送（札幌/富良野）'
  ],
  '這個體驗由札幌米其林一星餐廳主廚與北海道冒險公司聯手打造，每晚僅接待一組客人（2-6人）。圓頂帳篷每天現搭，確保您擁有完全的隱私與獨特視角。',
  4.0,
  2, 6,
  ARRAY['日語', '英語'],
  'easy',
  ARRAY['冬'],
  30,
  95000, 120000, 'JPY',
  ARRAY['往返接送', '10道式晚宴', '無限暢飲', '星空導覽', '暖爐與毛毯', '專業攝影'],
  18.00,
  ARRAY['honeymoon', 'anniversary', 'proposal', 'luxury_traveler', 'romantic'],
  '{"transportation": ["private_luxury_van"], "meals": ["10_course_dinner"], "drinks": ["champagne", "wine", "sake"], "extras": ["stargazing_guide", "campfire", "photography"]}',
  TRUE,
  TRUE,
  TRUE, TRUE
);

COMMIT;
