export const LABELS = {
  // 页面标题和导航
  EDIT_CONFIRMATION: '編輯確認單',
  CONFIRMATIONS_MANAGEMENT: '確認單管理',
  HOME: '首頁',
  
  // 按钮文字
  IMPORT_PNR: '匯入 PNR',
  PRINT: '列印',
  CANCEL: '取消',
  SAVE: '儲存中...',
  SAVING: '儲存中',
  UPDATE_CONFIRMATION: '更新確認單',
  BACK_TO_CONFIRMATIONS: '返回確認單列表',
  ADD: '新增',
  REMOVE: '移除',
  DELETE: '刪除',
  ADD_PHONE: '+ 新增電話',
  EDIT: '編輯',
  SEARCH: '搜尋',
  CONFIRM: '確認',
  CLOSE: '關閉',
  
  // 状态和消息
  LOADING: '載入中...',
  LOADING_SHORT: '載入中',
  PLEASE_WAIT: '請等待...',
  NOT_FOUND_TITLE: '找不到該確認單',
  NOT_FOUND_DESCRIPTION: '您要找的確認單可能已被刪除或不存在',
  
  // 表单验证和提示
  BOOKING_NUMBER_REQUIRED: '請填寫訂單編號',
  CONFIRMATION_UPDATED: '確認單已更新',
  UPDATE_FAILED: '更新失敗',
  PNR_IMPORT_SUCCESS: 'PNR 已成功匯入！',
  PNR_PARSE_SUCCESS: 'PNR 解析成功！',
  PNR_FORMAT_ERROR: 'PNR 格式錯誤，請檢查內容',
  PASTE_PNR_CONTENT: '請貼上 PNR 內容',
  
  // 航班相关
  ECONOMY_CLASS: '經濟',
  
  // 表单标签
  BOOKING_NUMBER: '訂單編號 *',
  CONFIRMATION_NUMBER: '飯店確認編號',
  HOTEL_INFO: '飯店資訊',
  HOTEL_NAME: '飯店名稱 *',
  HOTEL_ADDRESS: '地址 *',
  PHONE: '電話',
  CHECK_IN_INFO: '入住資訊',
  CHECK_IN_DATE: '入住日期 *',
  CHECK_IN_TIME: '入住時間',
  CHECK_OUT_DATE: '退房日期 *',
  CHECK_OUT_TIME: '退房時間',
  ROOM_COUNT: '房數 *',
  NIGHT_COUNT: '晚數 *',
  ROOM_INFO: '房型資訊',
  ROOM_TYPE: '房型 *',
  GUEST_NAME: '旅客姓名 *',
  GUEST_CAPACITY: '入住人數',
  MEAL_INFO: '餐點資訊',
  IMPORTANT_NOTES: '重要城市資訊 / 備註',
  
  // PrintableConfirmation.tsx
  FLIGHT_CONFIRMATION_TITLE: '機票確認單',
  ACCOMMODATION_CONFIRMATION_TITLE: '住宿確認單',
  BOOKING_CODE: '訂位代號',
  CONFIRMATION_CODE: '確認號碼',
  REMARKS: '備註',
  CORNER_TRAVEL: '角落旅行社',
  CORNER_TRAVEL_COMPANY: '角落旅行社股份有限公司',
  
  // Flight related
  DISCLAIMER: '**** 此文件資訊僅提供參考, 實際資訊以航空公司及相關旅遊供應商為準 ****',
  PASSENGER_NAME: '旅客姓名',
  DATE: '日期',
  TIME_FLIGHT: '時間  航班',
  OTHER_INFO: '其他訊息',
  DIRECT_FLIGHT: '直飛',
  TRANSIT: '轉機',
  DEPARTURE: '出發',
  ARRIVAL: '抵達',
  TERMINAL: '航站',
  MEAL: '餐點',
  TICKET_NUMBER: '機票號碼',
  AIRLINE_CONTACT: '航空公司確認電話',
  IMPORTANT_INFO: '重要資訊',
  
  // Accommodation related
  CHECK_IN: '入住',
  CHECK_OUT: '退房',
  ROOM_QUANTITY: '房間數量',
  ACCOMMODATION_DAYS: '住宿天數',
  ROOMS: '間',
  NIGHTS: '晚',
  ROOM_TYPE_COLON: '房型：',
  GUEST_NAME_COLON: '旅客姓名：',
  GUEST_CAPACITY_COLON: '入住人數：',
  MEAL_CONTENT: '餐點內容',
  
  // AccommodationForm.tsx additional labels
  ADD_MEAL: '+ 新增餐點',
  SELECT_DATE_PLACEHOLDER: '選擇日期',
  
  // FlightForm.tsx labels
  PASSENGER_INFO: '旅客資訊',
  EN_NAME: '英文姓名',
  ZH_NAME: '中文姓名',
  CABIN_CLASS: '艙等',
  TICKET_NO: '票號',
  BOOKING_CODE_LABEL: 'PNR',
  FLIGHT_INFO: '航班資訊',
  ROUTE: '航線',
  DEPARTURE_AIRPORT_LABEL: '出發機場',
  DEPARTURE_DATE_LABEL: '出發日期',
  DEPARTURE_TIME_LABEL: '出發時間',
  ARRIVAL_AIRPORT_LABEL: '抵達機場',
  ARRIVAL_DATE_LABEL: '抵達日期',
  ARRIVAL_TIME_LABEL: '抵達時間',
  AIRLINE_LABEL: '航空公司',
  FLIGHT_NUMBER_LABEL: '航班號',
  BAGGAGE_INFO: '行李資訊',
  PASSENGER_NAME_LABEL: '旅客姓名',
  PERSONAL_ITEM: '隨身物品',
  CARRY_ON: '手提行李',
  CHECKED_BAGGAGE: '託運行李',
  IMPORTANT_INFO_NOTES: '重要資訊',
  ADD_PASSENGER: '新增旅客',
  ADD_FLIGHT: '新增航班',
  ADD_BAGGAGE: '新增行李',
  ADD_NOTE: '新增重要資訊',
  BAGGAGE_DETAILS: '行李詳細資訊',
  CARRY_ON_DETAIL: '手提行李詳情',
  CHECKED_DETAIL: '託運行李詳情',
  PERSONAL_ITEM_DETAIL: '隨身物品詳情',
  ADD_BAGGAGE_DETAIL: '新增行李詳情',
  AIRLINE_CONTACT_INFO: '航空公司聯絡資訊'
} as const