export const LABELS = {
  // 页面标题和导航
  LIVE_PREVIEW: '即時預覽',
  EDIT_CONFIRMATION: '編輯確認單',
  CONFIRMATIONS_MANAGEMENT: '確認單管理',
  HOME: '首頁',
  
  // 按钮文字
  IMPORT_PNR: '匯入 PNR',
  PRINT: '列印',
  CANCEL: '取消',
  SAVE: '儲存中...',
  SAVING: '儲存中',
  UPDATE_CONFIRMATION: '更新確認單',
  BACK_TO_CONFIRMATIONS: '返回確認單列表',
  ADD: '新增',
  REMOVE: '移除',
  DELETE: '刪除',
  ADD_PHONE: '+ 新增電話',
  EDIT: '編輯',
  SEARCH: '搜尋',
  CONFIRM: '確認',
  CLOSE: '關閉',
  
  // 状态和消息
  LOADING: '載入中...',
  LOADING_SHORT: '載入中',
  PLEASE_WAIT: '請等待...',
  NOT_FOUND_TITLE: '找不到該確認單',
  NOT_FOUND_DESCRIPTION: '您要找的確認單可能已被刪除或不存在',
  
  // 表单验证和提示
  BOOKING_NUMBER_REQUIRED: '請填寫訂單編號',
  CONFIRMATION_UPDATED: '確認單已更新',
  UPDATE_FAILED: '更新失敗',
  PNR_IMPORT_SUCCESS: 'PNR 已成功匯入！',
  PNR_PARSE_SUCCESS: 'PNR 解析成功！',
  PNR_FORMAT_ERROR: 'PNR 格式錯誤，請檢查內容',
  PASTE_PNR_CONTENT: '請貼上 PNR 內容',
  
  // 航班相关
  ECONOMY_CLASS: '經濟',
  
  // 表单标签
  BOOKING_NUMBER: '訂單編號 *',
  CONFIRMATION_NUMBER: '飯店確認編號',
  HOTEL_INFO: '飯店資訊',
  HOTEL_NAME: '飯店名稱 *',
  HOTEL_ADDRESS: '地址 *',
  PHONE: '電話',
  CHECK_IN_INFO: '入住資訊',
  CHECK_IN_DATE: '入住日期 *',
  CHECK_IN_TIME: '入住時間',
  CHECK_OUT_DATE: '退房日期 *',
  CHECK_OUT_TIME: '退房時間',
  ROOM_COUNT: '房數 *',
  NIGHT_COUNT: '晚數 *',
  ROOM_INFO: '房型資訊',
  ROOM_TYPE: '房型 *',
  GUEST_NAME: '旅客姓名 *',
  GUEST_CAPACITY: '入住人數',
  MEAL_INFO: '餐點資訊',
  IMPORTANT_NOTES: '重要城市資訊 / 備註',
  
  // PrintableConfirmation.tsx
  FLIGHT_CONFIRMATION_TITLE: '機票確認單',
  ACCOMMODATION_CONFIRMATION_TITLE: '住宿確認單',
  BOOKING_CODE: '訂位代號',
  CONFIRMATION_CODE: '確認號碼',
  REMARKS: '備註',
  CORNER_TRAVEL: '角落旅行社',
  CORNER_TRAVEL_COMPANY: '角落旅行社股份有限公司',
  
  // Flight related
  DISCLAIMER: '**** 此文件資訊僅提供參考, 實際資訊以航空公司及相關旅遊供應商為準 ****',
  PASSENGER_NAME: '旅客姓名',
  DATE: '日期',
  TIME_FLIGHT: '時間  航班',
  OTHER_INFO: '其他訊息',
  DIRECT_FLIGHT: '直飛',
  TRANSIT: '轉機',
  DEPARTURE: '出發',
  ARRIVAL: '抵達',
  TERMINAL: '航站',
  MEAL: '餐點',
  TICKET_NUMBER: '機票號碼',
  AIRLINE_CONTACT: '航空公司確認電話',
  IMPORTANT_INFO: '重要資訊',
  
  // Accommodation related
  CHECK_IN: '入住',
  CHECK_OUT: '退房',
  ROOM_QUANTITY: '房間數量',
  ACCOMMODATION_DAYS: '住宿天數',
  ROOMS: '間',
  NIGHTS: '晚',
  ROOM_TYPE_COLON: '房型：',
  GUEST_NAME_COLON: '旅客姓名：',
  GUEST_CAPACITY_COLON: '入住人數：',
  MEAL_CONTENT: '餐點內容',
  
  // AccommodationForm.tsx additional labels
  ADD_MEAL: '+ 新增餐點',
  SELECT_DATE_PLACEHOLDER: '選擇日期',
  
  // FlightForm.tsx labels
  PASSENGER_INFO: '旅客資訊',
  EN_NAME: '英文姓名',
  ZH_NAME: '中文姓名',
  CABIN_CLASS: '艙等',
  TICKET_NO: '票號',
  BOOKING_CODE_LABEL: 'PNR',
  FLIGHT_INFO: '航班資訊',
  ROUTE: '航線',
  DEPARTURE_AIRPORT_LABEL: '出發機場',
  DEPARTURE_DATE_LABEL: '出發日期',
  DEPARTURE_TIME_LABEL: '出發時間',
  ARRIVAL_AIRPORT_LABEL: '抵達機場',
  ARRIVAL_DATE_LABEL: '抵達日期',
  ARRIVAL_TIME_LABEL: '抵達時間',
  AIRLINE_LABEL: '航空公司',
  FLIGHT_NUMBER_LABEL: '航班號',
  BAGGAGE_INFO: '行李資訊',
  PASSENGER_NAME_LABEL: '旅客姓名',
  PERSONAL_ITEM: '隨身物品',
  CARRY_ON: '手提行李',
  CHECKED_BAGGAGE: '託運行李',
  IMPORTANT_INFO_NOTES: '重要資訊',
  ADD_PASSENGER: '新增旅客',
  ADD_FLIGHT: '新增航班',
  ADD_BAGGAGE: '新增行李',
  ADD_NOTE: '新增重要資訊',
  BAGGAGE_DETAILS: '行李詳細資訊',
  CARRY_ON_DETAIL: '手提行李詳情',
  CHECKED_DETAIL: '託運行李詳情',
  PERSONAL_ITEM_DETAIL: '隨身物品詳情',
  ADD_BAGGAGE_DETAIL: '新增行李詳情',
  AIRLINE_CONTACT_INFO: '航空公司聯絡資訊',

  // ImportPNRDialog
  IMPORT_PNR_TITLE: '匯入 PNR 確認單',
  IMPORT_PNR_DESC: '貼上機票確認單的 HTML 或文字內容，系統會自動解析並填入表單',
  PNR_CONTENT_LABEL: 'PNR 內容',
  PARSING: '解析中...',
  PARSE_PNR: '解析 PNR',
  PARSE_SUCCESS_TITLE: '解析成功',
  RE_INPUT: '重新輸入',
  COMPUTER_CODE: '電腦代號：',
  PASSENGER_NAME_LABEL_COLON: '旅客姓名：',
  FLIGHT_INFO_LABEL: '航班資訊：',
  TICKET_NUMBER_LABEL: '機票號碼：',
  IMPORT_TO_CONFIRMATION: '匯入到確認單',
} as const
export const ACCOMMODATION_PREVIEW_LABELS = {
  HOTEL_VOUCHER_TITLE: '飯店入住憑證',
  BOOKING_NUMBER: '訂單編號',
  HOTEL_CONFIRMATION_NUMBER: '飯店確認編號',
  ADDRESS: '地址',
  PHONE: '電話',
  CHECK_IN: '入住',
  CHECK_OUT: '退房',
  DEFAULT_CHECK_IN_TIME: '14:00後',
  DEFAULT_CHECK_OUT_TIME: '12:00前',
  HOTEL_LOCAL_TIME: '飯店當地時間',
  ROOM: '房',
  NIGHT: '晚',
  ROOM_INFO: '房型資訊',
  GUEST_NAME: '旅客姓名',
  YOUR_BOOKING: '您的預訂',
  ROOMS_UNIT: '間房，',
  NIGHTS_UNIT: '晚',
  GUEST_CAPACITY: '入住人數',
  MEAL_INFO: '餐點資訊',
  IMPORTANT_CITY_INFO: '重要城市資訊',
  FOOTER: 'VENTURO | 專業旅遊服務',
  MONTH_SUFFIX: '月',
  DAY_SUFFIX: '日',
}

export const ACCOMMODATION_FORM_LABELS = {
  HOTEL_NAME_PLACEHOLDER: '凡裡FUN LIST飯店（上海顓橋萬達店）',
  ADDRESS_PLACEHOLDER: '上海, 閔行區, 顓興東路1398號',
  CHECK_IN_TIME_PLACEHOLDER: '14:00後',
  CHECK_OUT_TIME_PLACEHOLDER: '12:00前',
  ROOM_TYPE_PLACEHOLDER: '凡趣大床房（全屋智能+手機投屏+零壓床品+65吋電視）',
  GUEST_CAPACITY_PLACEHOLDER: '此房型可容納最多 2 位旅客，其中最多 2 位成人',
  MEAL_PLACEHOLDER: '每房 1 客早餐',
  NOTES_PLACEHOLDER: '特殊規定、注意事項...',
}

export const FLIGHT_PREVIEW_LABELS = {
  COMPUTER_CODE: '電腦代號',
  NOT_FILLED: '尚未填寫',
  DISCLAIMER: '**** 此文件資訊僅供參考, 實際資訊以航空公司及相關旅遊供應商為準 ****',
  PASSENGER_NAME: '旅客姓名',
  DATE_HEADER: '日 期',
  TIME_FLIGHT_HEADER: '時 間  航 班',
  OTHER_INFO_HEADER: '其 他 訊 息',
  DIRECT_FLIGHT: '直飛',
  DEPARTURE_PREFIX: '出發',
  ARRIVAL_PREFIX: '抵達',
  TERMINAL: '航站',
  DEFAULT_CABIN: '經濟',
  MEAL: '餐點',
  TICKET_NUMBER: '機票號碼',
  AIRLINE_CONTACT: '航空公司確認電話',
  IMPORTANT_INFO: '重要資訊',
}

export const FLIGHT_FORM_LABELS = {
  DEFAULT_CABIN: '經濟艙',
  ZH_NAME_PLACEHOLDER: '宋紹慶',
  ROUTE_PLACEHOLDER: '台北 - 上海',
  SELECT_DATE_PLACEHOLDER: '選擇日期',
  DEPARTURE_TIME: '出發時間',
  DEPARTURE_AIRPORT: '出發機場',
  DEPARTURE_AIRPORT_PLACEHOLDER: '台灣桃園國際機場 T2',
  ARRIVAL_AIRPORT: '抵達機場',
  ARRIVAL_AIRPORT_PLACEHOLDER: '浦東國際機場 T2',
  AIRLINE: '航空公司',
  AIRLINE_PLACEHOLDER: '中國南方航空股份有限公司',
  FLIGHT_NUMBER: '航班號',
  ADD_FLIGHT: '+ 新增航班',
  BAGGAGE_ALLOWANCE: '行李額度',
  PASSENGER_NAME: '旅客姓名',
  PASSENGER_NAME_PLACEHOLDER: 'SUNG SHAOCHING (成人)',
  PERSONAL_ITEM: '個人物品',
  PERSONAL_ITEM_PLACEHOLDER: '每人 1 件',
  CARRY_ON: '手提行李',
  CARRY_ON_PLACEHOLDER: '每人 1 件，每件 8 公斤',
  CHECKED_BAGGAGE: '託運行李',
  CHECKED_BAGGAGE_PLACEHOLDER: '每人 1 件，每件 23 公斤',
  ADD_BAGGAGE: '+ 新增行李額度',
  IMPORTANT_INFO: '重要資訊',
  NOTE_LABEL: '注意事項',
  NOTE_PLACEHOLDER: '在機場的各項登機手續中，乘客須出示購買機票時使用的個人身分證明文件...',
  ADD_NOTE: '+ 新增注意事項',
  BAGGAGE_DETAIL_TITLE: '行李詳細資訊',
  SEGMENT_LABEL: '航段',
  SEGMENT_PLACEHOLDER: '台北 - 上海',
  CARRY_ON_DETAIL: '手提行李詳情',
  CARRY_ON_DETAIL_PLACEHOLDER: '每人 1 件，每件 8 公斤 每件尺寸上限 55x40x20 公分',
  CHECKED_DETAIL: '託運行李詳情',
  CHECKED_DETAIL_PLACEHOLDER: '每人 1 件，每件 23 公斤 每件尺寸 (長+寬+高) 上限 158 公分',
  PERSONAL_ITEM_DETAIL: '個人物品詳情',
  PERSONAL_ITEM_DETAIL_PLACEHOLDER: '每人 1 件 請聯繫航空公司以進一步了解行李政策 必須置於您前面座位的下方。',
  ADD_BAGGAGE_DETAIL: '+ 新增行李詳細資訊',
}
