-- =====================================================
-- 清理並禁用所有表格的 RLS
-- 建立日期：2025-11-17
-- 目的：最終確認所有 RLS 已禁用
-- =====================================================

-- 禁用所有表格的 RLS（不使用 DO 區塊，避免 schema_migrations 衝突）
ALTER TABLE IF EXISTS public.accounting_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.accounting_voucher_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.accounting_vouchers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.airports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bank_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.calendar_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channel_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contract_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.cost_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.esims DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.itineraries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.itinerary_days DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.link_pay_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.order_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payment_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pnrs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.price_lists DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quick_quote_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quick_quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.receipt_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.todos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_departure_accommodations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_departure_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_departure_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_departure_meals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_departure_others DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tour_member_fields DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tours DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.transportation_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.visas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workspaces DISABLE ROW LEVEL SECURITY;

-- 查詢結果並輸出報告
SELECT
  '✅ RLS 禁用完成' as status,
  COUNT(*) as total_tables,
  SUM(CASE WHEN rowsecurity THEN 1 ELSE 0 END) as rls_enabled_count
FROM pg_tables
WHERE schemaname = 'public';
