export const PROPOSAL_LABELS = {
  // === Status ===
  status: {
    draft: '草稿',
    negotiating: '洽談中',
    converted: '已轉團',
    archived: '已封存',
  },

  // === ArchiveProposalDialog ===
  archiveDialog: {
    title: '封存提案',
    submitLabel: '確認封存',
    confirmMessage: (title?: string) => `確定要封存提案「${title}」嗎？封存後將無法繼續編輯。`,
    reasonLabel: '封存原因',
    reasonPlaceholder: '請選擇封存原因...',
    customReasonLabel: '說明',
    customReasonPlaceholder: '請說明封存原因...',
  },

  // === ProposalDialog ===
  proposalDialog: {
    createTitle: '新增提案',
    editTitle: '編輯提案',
    proposalNameLabel: '提案名稱',
    proposalNamePlaceholder: '例如：2026 泰北清邁家族旅遊',
    expectedDateLabel: '預計出發日期（選填）',
    versionNameLabel: '版本名稱',
    versionNamePlaceholder: '例如：方案A - 經濟版',
    departDateLabel: '出發日期',
    returnDateLabel: '回程日期',
    datePlaceholder: '選擇日期',
    groupSizeLabel: '預計人數',
    groupSizePlaceholder: '人數',
    notesLabel: '備註',
    notesPlaceholder: '版本相關備註...',
    cancel: '取消',
    creating: '建立中...',
    createProposal: '建立提案',
    save: '儲存',
  },

  // === ProposalDetailDialog ===
  detailDialog: {
    title: (code: string) => `提案詳情 - ${code}`,
    unnamed: '(未命名)',
    addVersion: '新增版本',
  },

  // === ProposalsTableContent ===
  table: {
    codeCol: '團號',
    titleCol: '旅遊團名稱',
    departDateCol: '出發日期',
    destinationCol: '目的地',
    statusCol: '狀態',
    editAction: '編輯',
    archiveAction: '封存',
    deleteAction: '刪除',
    emptyMessage: '尚無提案資料',
    cannotGetInfo: '無法取得資訊',
    updateFailed: '更新提案失敗',
    deleteConfirm: (title?: string) => `確定要刪除提案「${title}」嗎？`,
    deletePackageWarning: (count: number) => `\n\n注意：此提案有 ${count} 個套件，將一併刪除`,
    deleteTitle: '刪除提案',
    deleteFailed: '刪除提案失敗',
    archiveFailed: '封存提案失敗',
  },

  // === PackageListPanel ===
  packageList: {
    noVersions: '尚無版本',
    versionCol: '版本',
    destinationCol: '目的地',
    dateCol: '日期',
    groupSizeCol: '人數',
    operationsCol: '操作',
    personUnit: (n: number) => `${n}人`,
    itineraryTitle: '行程表',
    brochurePreviewTitle: '簡易行程預覽',
    webItineraryTitle: '網頁行程',
    viewQuote: '查看報價單',
    createQuote: '建立報價單',
    requirementTitle: '需求確認單',
    brochureDesignTitle: '手冊設計',
    copyTitle: '複製',
    editTitle: '編輯',
    deleteTitle: '刪除',
    convertToTour: '轉開團',
    pleaseCreateItinerary: '請先建立行程表',
    pleaseCreateQuote: '請先建立報價單',
    cannotGetUserInfo: '無法取得使用者資訊',
    createPackageFailed: '建立套件失敗',
    updatePackageFailed: '更新套件失敗',
    copyPackageFailed: '複製套件失敗',
    copySuffix: '(複製)',
    deleteConfirm: (name: string) => `確定要刪除套件「${name}」嗎？`,
    deleteDialogTitle: '刪除套件',
    deletePackageFailed: '刪除套件失敗',
    createQuoteFailed: '建立報價單失敗',
    customerPlaceholder: '待填寫',
    selfCatering: '自理',
  },

  // === PackageDialog ===
  packageDialog: {
    createTitle: '新增團體套件',
    editTitle: '編輯團體套件',
    createSubmit: '建立',
    editSubmit: '儲存',
    versionNameLabel: '版本名稱',
    versionNamePlaceholder: '例如：方案A - 經濟版',
    departDateLabel: '出發日期',
    returnDateLabel: '回程日期',
    datePlaceholder: '選擇日期',
    groupSizeLabel: '預計人數',
    groupSizePlaceholder: '人數',
    notesLabel: '備註',
    notesPlaceholder: '套件相關備註...',
  },

  // === AddManualRequestDialog ===
  addRequestDialog: {
    title: '手動新增需求',
    categoryLabel: '需求類別',
    categoryPlaceholder: '選擇類別',
    titleLabel: '項目說明',
    titlePlaceholder: '例如：機場接送、全程領隊',
    supplierLabel: '供應商/廠商名稱',
    supplierPlaceholder: '例如：車行名稱、領隊姓名',
    sendToSupplierLabel: '發送給供應商',
    loadingPlaceholder: '載入中...',
    selectSupplierPlaceholder: '選擇供應商（選填）',
    internalHandling: '不發送（內部處理）',
    vehicleInfoTitle: '車輛資訊（供應商回覆後填寫）',
    driverLabel: '司機',
    driverPlaceholder: '司機姓名',
    plateLabel: '車號',
    platePlaceholder: '車牌號碼',
    phoneLabel: '手機',
    phonePlaceholder: '司機電話',
    selectFromDbLabel: '從資料庫選擇',
    selectRestaurant: '選擇餐廳',
    selectHotel: '選擇飯店',
    selectAttraction: '選擇景點',
    startDateLabel: '開始日期',
    endDateLabel: '結束日期',
    quantityLabel: '數量',
    quantityUnit: {
      transport: '台數',
      guide: '人數',
      accommodation: '間數',
      meal: '人數',
      activity: '人數',
      other: '數量',
    } as Record<string, string>,
    remarksLabel: '備註說明',
    remarksPlaceholder: '其他需求說明...',
    cancel: '取消',
    saveBtn: '儲存',
    pleaseLogin: '請先登入',
    requestAdded: '需求已新增',
    addFailed: '新增失敗',
  },

  // === Categories ===
  categories: {
    transport: '交通（派車）',
    guide: '領隊',
    accommodation: '住宿',
    meal: '餐食',
    activity: '門票/活動',
    other: '其他',
  },

  // === BrochurePreviewDialog ===
  brochurePreview: {
    title: '簡易行程表',
    print: '列印',
    mainVersion: '主版本',
    versionLabel: (version: number) => `版本 ${version}`,
    notFound: '找不到行程表',
    defaultCompany: '旅行社',
    destinationLabel: '目的地：',
    departDateLabel: '出發日期：',
    daysLabel: '行程天數：',
    daysUnit: (n: number) => `${n} 天`,
    dateCol: '日期',
    contentCol: '行程內容',
    breakfastCol: '早餐',
    lunchCol: '午餐',
    dinnerCol: '晚餐',
    hotelCol: '住宿',
    footer: (company: string) => `本行程表由 ${company} 提供`,
    printFooter: (company: string, date: string) => `本行程表由 ${company} 提供 | 列印日期：${date}`,
  },

  // === RequirementSyncDialog ===
  requirementSync: {
    title: '需求確認單',
    quoteUpdated: '報價單已更新',
    quoteUpdatedDesc: '需求總覽將自動刷新',
    close: '關閉',
  },

  // === SupplierSearchInput ===
  supplierSearch: {
    placeholder: '輸入供應商名稱',
    notFound: (term: string) => `找不到「${term}」`,
    useAs: (term: string) => `使用「${term}」`,
    contactLabel: '聯絡人: ',
  },

  // === TourRequestFormDialog ===
  requestForm: {
    requestFormSuffix: '需求單',
    categoryNames: {
      hotel: '住宿',
      restaurant: '餐飲',
      transport: '交通',
      activity: '門票/活動',
      other: '其他',
    } as Record<string, string>,
    categoryColumns: {
      hotel: { dateLabel: '日期', titleLabel: '房型', qtyLabel: '間數' },
      restaurant: { dateLabel: '日期', titleLabel: '餐別', qtyLabel: '人數' },
      transport: { dateLabel: '日期', titleLabel: '路線/車型', qtyLabel: '台數' },
      activity: { dateLabel: '日期', titleLabel: '項目', qtyLabel: '人數' },
      other: { dateLabel: '日期', titleLabel: '項目', qtyLabel: '數量' },
    } as Record<string, { dateLabel: string; titleLabel: string; qtyLabel: string }>,
    ourInfoTitle: '我方資訊',
    vendorInfoTitle: '廠商資訊',
    companyLabel: '公司：',
    phoneLabel: '電話：',
    faxLabel: '傳真：',
    salesLabel: '業務：',
    assistantLabel: '助理：',
    vendorLabel: '廠商：',
    cityLabel: '城市：',
    contactLabel: '聯絡人：',
    tourCodeLabel: '團號：',
    tourNameLabel: '團名：',
    departDateLabel: '出發日期：',
    groupSizeLabel: '人數：',
    personUnit: '人',
    unitPriceCol: '單價',
    noteCol: '備註',
    operationCol: '操作',
    addItem: '新增項目',
    close: '關閉',
    createPaymentRequest: '建立請款單',
    printBtn: '列印',
    requestSentAndSaved: '需求單已發送並存檔',
    statusUpdated: '狀態已更新為「已發送」',
    saveFailed: '存檔失敗',
    saveFailedDesc: '請重試或聯繫系統管理員',
    allowPopup: '請允許彈出視窗以進行列印',
    defaultCompany: '角落旅行社',
  },

  // === ItineraryDialog ===
  itineraryDialog: {
    title: '時間軸行程編輯器',
    itineraryTitleLabel: '行程標題',
    itineraryTitlePlaceholder: '輸入行程標題...',
    subtitleLabel: '副標題',
    subtitlePlaceholder: '輸入副標題...',
    todayThemeLabel: '今日主題',
    titleInputPlaceholder: '台北 ✈ 福岡空港 → 由布院 · 金麟湖 → 阿蘇溫泉',
    deleteDay: '刪除此天',
    startCol: '開始',
    endCol: '結束',
    attractionCol: '景點/餐廳',
    menuCol: '菜色',
    mealCol: '餐食',
    photoCol: '照片',
    colorCol: '色',
    restaurantNamePlaceholder: '餐廳名稱',
    attractionNamePlaceholder: '景點名稱',
    menuPlaceholder: '菜色內容',
    addFromDb: '從景點庫新增',
    addManual: '手動新增',
    uploadedPhotos: '已上傳照片：',
    attractionDefault: '景點',
    hotelLabel: '當晚住宿：',
    hotelPlaceholder: '輸入飯店名稱...',
    selectFromHotelDb: '從飯店庫選擇',
    close: '關閉',
    print: '列印',
    saveBtn: '儲存',
    saving: '儲存中...',
    saveNotEnabled: '儲存功能未啟用',
    saveSuccess: '儲存成功',
    saveFailed: '儲存失敗',
    insertArrow: '插入箭頭',
    insertHookArrow: '插入鉤箭頭',
    insertDot: '插入間隔點',
    insertLine: '插入直線',
    insertStar: '插入星號',
    insertPlane: '插入飛機',
    insertAttractionBelow: '在此行下方插入景點',
    uploadPhoto: '上傳照片',
    selectColor: '選擇顏色',
    addDay: '新增一天',
    colorOptions: {
      default: '預設',
      blue: '藍色',
      red: '紅色',
      green: '綠色',
      orange: '橙色',
      purple: '紫色',
    },
    defaultTitle: '行程表',
  },

  // === AiGenerateDialog ===
  aiDialog: {
    title: 'AI 排行程',
    destinationLabel: '目的地',
    notSet: '未設定',
    daysLabel: '天數',
    daysUnit: (n: number) => `${n} 天`,
    accommodationStatusLabel: '住宿狀態',
    accommodationFilled: (filled: number, total: number) => `✓ 已填寫 ${filled}/${total} 天`,
    arrivalTimeLabel: '第一天抵達時間',
    departureTimeLabel: '最後一天離開時間',
    themeLabel: '行程風格',
    description: 'AI 將根據您的住宿地點和選擇的風格，為每一天安排合適的景點和路線',
    cancel: '取消',
    generating: '生成中...',
    generate: '生成行程',
  },

  // === DailyScheduleEditor ===
  dailyEditor: {
    arriveDestination: '抵達目的地',
    returnTaiwan: '返回台灣',
    todayItineraryTitle: '今日行程標題',
    hotelBreakfast: '飯店早餐',
    selfCatering: '敬請自理',
    breakfast: '早餐',
    lunch: '午餐',
    dinner: '晚餐',
    hotelPlaceholder: '住宿飯店',
    hotelBreakfastCheckbox: '飯店早餐',
    selfCateringCheckbox: '敬請自理',
    stayCheckbox: '續住',
    samePreviousPrefix: '同上',
  },

  // === FlightSection ===
  flightSection: {
    title: '航班資訊（選填）',
    outboundLabel: '去程航班',
    returnLabel: '回程航班',
    multiSegment: '此航班有多個航段，請選擇：',
    cancelBtn: '取消',
    flightNumberPlaceholder: (example: string) => `航班號碼 (如 ${example})`,
    datePlaceholder: '日期',
  },

  // === ItineraryPreview (shared labels) ===
  itineraryPreview: {
    title: '簡易行程表',
    editBtn: '編輯',
    printBtn: '列印',
    defaultTitle: '行程表',
    destinationLabel: '目的地：',
    departDateLabel: '出發日期：',
    daysLabel: '行程天數：',
    daysUnit: (n: number) => `${n} 天`,
    outboundFlightLabel: '去程航班：',
    returnFlightLabel: '回程航班：',
    dateCol: '日期',
    contentCol: '行程內容',
    breakfastCol: '早餐',
    lunchCol: '午餐',
    dinnerCol: '晚餐',
    hotelCol: '住宿',
    footer: (company: string) => `本行程表由 ${company} 提供`,
  },

  // === PackageItineraryDialog ===
  packageItinerary: {
    loading: '載入中...',
    editTitle: '編輯行程表',
    createTitle: '建立行程表',
    previewBtn: '預覽',
    itineraryTitleLabel: '行程標題 *',
    itineraryTitlePlaceholder: '行程表標題',
    destinationLabel: '目的地',
    notSet: '(未設定)',
    daysLabel: '行程天數',
    daysUnit: (n: number) => `${n} 天`,
    departDateLabel: '出發日期',
    returnDateLabel: '回程日期',
    aiBtn: 'AI 排行程',
    saveAsNewVersion: '另存新版本',
    update: '更新行程',
    create: '建立行程',
    timelineMode: '時間軸行程',
    simpleMode: '每日行程',
    switchSimple: '簡易模式',
    switchTimeline: '時間軸',
    switchSimpleTitle: '切換簡易模式',
    switchTimelineTitle: '切換時間軸模式',
    defaultCompany: '旅行社',
  },

  // === TimelineEditor ===
  timelineEditor: {
    addActivity: '新增活動',
    arriveDestination: '抵達目的地',
    returnTaiwan: '返回台灣',
    todayItineraryTitle: '今日行程標題',
    hotelBreakfast: '飯店早餐',
    selfCatering: '敬請自理',
    breakfast: '早餐',
    lunch: '午餐',
    dinner: '晚餐',
    hotelPlaceholder: '住宿飯店',
    hotelBreakfastCheckbox: '飯店早餐',
    selfCateringCheckbox: '敬請自理',
    stayCheckbox: '續住',
    samePreviousPrefix: '同上',
    timeCol: '時間',
    contentCol: '活動內容',
    attractionPlaceholder: '景點名稱',
    noActivities: '點擊「新增活動」加入景點',
  },

  // === VersionDropdown ===
  versionDropdown: {
    historyLabel: (count: number) => `版本歷史 (${count})`,
    mainVersion: '主版本',
    mainVersionBadge: '主版本',
    currentBadge: '當前',
    currentEditing: '當前編輯中',
    versionLabel: (version: number) => `版本 ${version}`,
  },

  // === Common ===
  required: '*',
} as const
