export const LABELS = {
  // FileList
  searchFiles: '搜尋檔案...',
  category: '分類',
  categoryAll: '全部',
  upload: '上傳',
  loading: '載入中...',
  noFilesInFolder: '此資料夾沒有檔案',
  uploadFile: '上傳檔案',
  selectedFiles: (count: number) => `已選取 ${count} 個檔案`,
  totalFiles: (count: number) => `共 ${count} 個檔案`,

  // FilePreview
  selectFileToPreview: '選取檔案以預覽',
  batchDownload: '下載所選檔案',
  moveTo: '移動到...',
  delete: '刪除所選',
  totalSize: (size: string) => `總大小：${size}`,
  fileLabel: '檔案',
  download: '下載',
  openInNewTab: '開啟',
  categoryLabel: '分類',
  sizeLabel: '大小',
  typeLabel: '類型',
  createdDate: '建立日期',
  downloadCount: '下載次數',
  tagsLabel: '標籤',
  description: '描述',
  notes: '備註',
  deleteFile: '刪除檔案',

  // FolderTree
  fileManager: '檔案總管',
  newSubfolder: '新增子資料夾',
  rename: '重新命名',
  deleteFolder: '刪除',
  allFiles: '所有檔案',
  loadingEllipsis: '載入中...',
  noFolders: '尚無資料夾',

  // UploadDialog
  uploadFiles: '上傳檔案',
  dragDropHere: '拖放檔案到這裡',
  orClickToSelect: '或點擊選擇檔案',
  uploadTo: '上傳至：',
  close: '關閉',
  cancel: '取消',
  uploading: '上傳中...',
  uploadCount: (count: number) => `上傳 ${count} 個檔案`,
}
export const FILES_LABELS = {
  DOWNLOAD: '下載',
  LABEL_725: '重新命名',
  DELETE: '刪除',
  LABEL_6285: '根目錄',
  ADD: '新增',
  ADD_7926: '新增資料夾',
  UPLOADING_209: '上傳檔案',
  EMPTY_351: '尚無資料',
}
